<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
  <head>
    <meta charset="utf-8" />
    <meta name="generator" content="pandoc" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=yes"
    />
    <title>report</title>
    <style>
      /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
      code {
        white-space: pre-wrap;
      }
      span.smallcaps {
        font-variant: small-caps;
      }
      div.columns {
        display: flex;
        gap: min(4vw, 1.5em);
      }
      div.column {
        flex: auto;
        overflow-x: auto;
      }
      div.hanging-indent {
        margin-left: 1.5em;
        text-indent: -1.5em;
      }
      /* The extra [class] is a hack that increases specificity enough to
       override a similar rule in reveal.js */
      ul.task-list[class] {
        list-style: none;
      }
      ul.task-list li input[type="checkbox"] {
        font-size: inherit;
        width: 0.8em;
        margin: 0 0.8em 0.2em -1.6em;
        vertical-align: middle;
      }
    </style>
    <link rel="stylesheet" href="style.css" />
    <script
      defer=""
      src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js"
      type="text/javascript"
    ></script>
  </head>
  <body>
    <nav id="TOC" role="doc-toc">
      <h2>Table of Contents</h2>
      <ul>
        <li><a href="#abstract">Abstract</a></li>
        <li><a href="#introduction">Introduction</a></li>
        <li><a href="#methodology-and-data">Methodology and Data</a></li>
        <li><a href="#eda-1">EDA</a></li>
        <li><a href="#modelling">Modelling</a></li>
        <li>
          <a href="#modelling-δ-inflation---sarimax">SARIMAX Inflation Model</a>
        </li>
        <li>
          <a href="#macroeconomic-system-analysis-a-var-approach"
            >VAR System Model</a
          >
        </li>
        <li>
          <a href="#yield-curve-based-recession-prediction-3-month-forecast"
            >Recession Prediction</a
          >
        </li>
        <li><a href="#project-conclusion">Project Conclusion</a></li>
        <li><a href="#limitations">Limitations</a></li>
        <li><a href="#future-works">Future Work</a></li>
      </ul>
    </nav>
    <h1 id="abstract">Abstract</h1>
    <p>
      This project is dedicated to analyzing the drivers of inflation in the
      United States and attempting to create a forecasting model that can
      predict whether inflation will rise or fall. The study uses a monthly set
      of macroeconomic data from 1958–2024 from FRED, BLS, BEA, EIA, and the
      U.S. Treasury Department. The study includes measures of consumer prices,
      labor markets, GDP growth, energy markets, external balances, interest
      rates, yield curve spreads, and inflation expectations.
    </p>
    <p>
      The analysis begins with the Phillips curve model, which was widely
      accepted from the late 1950s to the early 1970s as the primary tool for
      explaining and forecasting inflation. The study’s findings show that in
      modern economies, unemployment currently explains little of the variation
      in inflation, suggesting that the drivers of the economy have changed. We
      added variables for energy shocks, global linkages, and monetary policy to
      the simulation. Using a linear model, we identified five key predictors of
      inflation: changes in oil prices, natural gas prices, GDP growth, and
      short- and long-term inflation dynamics. To complement this structural
      approach, a Vector Autoregression (VAR) model was also estimated to
      capture the dynamic interactions among macroeconomic variables and to
      examine how shocks propagate across the economic system.
    </p>
    <p>
      We also developed models for forecasting the economy. Comparing the
      results of the models, we found that SARIMAX was the best. We also tested
      the robustness of the model through horizon-based cross-validation. The
      final model produces inflation forecasts for the next two years. We also
      developed a model that signals recession warnings. Together, these results
      provide insight into the drivers of the economy and inflation dynamics in
      the United States.
    </p>
    <h1 id="introduction">Introduction</h1>
    <p>
      Inflation remains one of the most persistent and difficult-to-explain
      macroeconomic phenomena. Although classical economic theory links
      inflation to a decline in the labor market, this connection has weakened
      significantly in recent decades. Therefore, current research relies on a
      handful of other driving forces that stimulate a sharp increase in
      inflation. Analysis of inflation peaks shows that the reasons for the
      rapid increase are the recovery of oil prices, trade disruptions, the
      pandemic and aggressive monetary policy. Therefore, we decided to add
      domestic, global and financial market forces to the predictor variables.
    </p>
    <p>
      For the study, a monthly data set for 1958–2024 was taken from the main US
      macroeconomic institutions, such as FRED, BLS, BEA, EIA, and the Treasury
      Department. The data set includes: consumer prices, employment trends, GDP
      growth, commodity markets, external balances, interest rates, the yield
      curve, and inflation expectations.
    </p>
    <p>
      A linear regression model was developed to determine the relationships
      between variables and inflation. Five variables were selected using subset
      selection. As a result, the most influential variables were oil and
      natural gas prices, with GDP growth and short-term inflation persistence
      as the main factors. To complement this static analysis, a Vector
      Autoregression (VAR) model was also estimated to capture dynamic
      interactions among inflation, labor markets, interest rates, and energy
      prices. Unlike the linear model, VAR incorporates lag structures directly
      and allows the system of variables to influence each other over time.
      However, the VAR model is less interpretable than the linear model,
      because the linear model focuses on the structural contribution of each
      predictor in an easy-to-explain way (for example: a 1% rise in oil prices
      increases inflation by …). While VAR provides a representation of how
      shocks propagate through the economy. Its value comes from modeling how
      changes in one variable influence others over multiple periods.
    </p>
    <p>
      In addition to these structural analyses, the project also develops a more
      advanced time series forecasting framework using SARIMAX models. Since
      inflation exhibits persistence, volatility clustering, and potential
      structural disruptions, some preliminary training is required. The target
      variable is defined as the logarithmic annual change in the core CPI,
      whose differential form is shown to be stationary by ADF and KPSS testing.
      A systematic grid search is performed for seasonal and non-seasonal SARIMA
      parameters, followed by a multi-stage variable screening process to
      identify significant exogenous predictors. Seven macroeconomic variables,
      including the unemployment gap, gasoline prices, expected inflation, the
      federal funds rate, and the 10-year–3-month bond yield spread, are tested
      for stationarity and included in either differential or level form, as
      appropriate.
    </p>
    <p>
      The model is evaluated against statistical criteria such as coefficient
      significance, residual whiteness using the Lung-Box test, valid standard
      errors, and savings. We also use the mean absolute scaled error (MASE) and
      Theil’s U-statistic as performance measures. A 108-fold expanding window
      validation is used to assess robustness over forecast horizons of one to
      twelve months. After filtering over eight million candidate
      specifications, the model selected for final forecasting is the
      SARIMA(1,1,1)(0,0,2)[12] structure, augmented with a three-month lag
      differential federal funds rate. Performance deteriorates somewhat as
      forecast horizons increase. Nevertheless, the model provides a reliable
      short-term forecast and is used to generate inflation forecasts for the
      next two years.
    </p>
    <p>
      Along with SARIMAX, the VAR model is used to assess the behavior of
      inflation forecasts in a multivariate environment. Although its
      within-sample forecasting accuracy is lower in the short term, the model
      is more stable for medium- and long-term forecasts. VAR also explains how
      shocks propagate across variables, making it valuable for understanding
      the mechanisms of the economy.
    </p>
    <p>
      Finally, the project extends the analysis by building a recession warning
      model based on yield curve signals and macro-financial indicators,
      offering an integrated view of economic risks.
    </p>
    <p>
      This work combines structural economic analysis with time series modeling
      using the SARIMA model and dynamic multivariate modeling through VAR to
      provide insight into the dynamics of inflation in the United States. Using
      macroeconomic variables, the project identifies factors that influence
      inflation and provides a model that predicts inflation for the next two
      years with reasonable accuracy.
    </p>
    <h1 id="methodology-and-data">Methodology and Data</h1>
    <p>
      <strong><em>Dataset file:</em></strong> economic_combined_data.csv
    </p>
    <p>
      This dataset integrates a comprehensive set of U.S. macroeconomic
      indicators used to analyze the joint dynamics of inflation, labor market
      conditions, wages, interest rates, trade flows, and commodity prices. All
      variables are observed at a monthly frequency and are primarily sourced
      from FRED (Federal Reserve Economic Data) and the Bureau of Labor
      Statistics (BLS). In addition to directly imported series, several
      variables are constructed as growth rates, percentage changes, or
      logarithmic transformations to support econometric modeling and
      time-series analysis.
    </p>
    <p>
      <strong><em>Sample period:</em></strong> February 1957 – September 2025
    </p>
    <p><span id="_Toc216111451" class="anchor"></span></p>
    <h2 id="columns-and-descriptions">Columns and Descriptions</h2>
    <table style="width: 98%">
      <colgroup>
        <col style="width: 31%" />
        <col style="width: 28%" />
        <col style="width: 22%" />
        <col style="width: 15%" />
      </colgroup>
      <thead>
        <tr>
          <th style="text-align: left">Variable</th>
          <th style="text-align: left">Description</th>
          <th style="text-align: left">Source</th>
          <th style="text-align: left">Unit</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="text-align: left"><code>date</code></td>
          <td style="text-align: left">
            Monthly observation date used as the time index
          </td>
          <td style="text-align: left">—</td>
          <td style="text-align: left">YYYY-MM-DD</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>cpi</code></td>
          <td style="text-align: left">
            Consumer Price Index (All Urban Consumers, All Items)
          </td>
          <td style="text-align: left">FRED (<code>CPIAUCSL</code>)</td>
          <td style="text-align: left">Index (1982–1984 = 100)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>core_cpi</code></td>
          <td style="text-align: left">Core CPI excluding food and energy</td>
          <td style="text-align: left">FRED (<code>CPILFESL</code>)</td>
          <td style="text-align: left">Index (1982–1984 = 100)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>cpi_energy</code></td>
          <td style="text-align: left">Energy component of CPI</td>
          <td style="text-align: left">BLS (<code>CUUR0000SA0E</code>)</td>
          <td style="text-align: left">Index</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>cpi_food_beverages</code></td>
          <td style="text-align: left">Food and beverages CPI component</td>
          <td style="text-align: left">BLS (<code>CUUR0000SAF</code>)</td>
          <td style="text-align: left">Index</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>cpi_housing</code></td>
          <td style="text-align: left">Housing CPI component</td>
          <td style="text-align: left">BLS (<code>CUUR0000SAH</code>)</td>
          <td style="text-align: left">Index</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>cpi_medical</code></td>
          <td style="text-align: left">Medical care CPI component</td>
          <td style="text-align: left">BLS (<code>CUUR0000SAM</code>)</td>
          <td style="text-align: left">Index</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>cpi_transportation</code></td>
          <td style="text-align: left">Transportation CPI component</td>
          <td style="text-align: left">BLS (<code>CUUR0000SAT</code>)</td>
          <td style="text-align: left">Index</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>inflation_rate</code></td>
          <td style="text-align: left">Month-over-month CPI inflation rate</td>
          <td style="text-align: left">Derived</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>core_inflation_rate</code></td>
          <td style="text-align: left">Month-over-month core inflation rate</td>
          <td style="text-align: left">Derived</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>inflation_yoy</code></td>
          <td style="text-align: left">Year-over-year CPI inflation rate</td>
          <td style="text-align: left">Derived</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>core_inflation_yoy</code></td>
          <td style="text-align: left">
            Year-over-year core CPI inflation rate
          </td>
          <td style="text-align: left">Derived</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>log_inflation_mom</code></td>
          <td style="text-align: left">Log month-over-month core inflation</td>
          <td style="text-align: left">Derived</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>log_inflation_yoy</code></td>
          <td style="text-align: left">Log year-over-year core inflation</td>
          <td style="text-align: left">Derived</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>unemployment_rate</code></td>
          <td style="text-align: left">Civilian unemployment rate</td>
          <td style="text-align: left">BLS (<code>LNS14000000</code>)</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>unemp_noncyclical</code></td>
          <td style="text-align: left">Natural rate of unemployment (NROU)</td>
          <td style="text-align: left">FRED (<code>NROU</code>)</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>unemp_24_54_yrs</code></td>
          <td style="text-align: left">Unemployment rate, ages 24–54</td>
          <td style="text-align: left">FRED (<code>LNS14000060</code>)</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>unemp_gap</code></td>
          <td style="text-align: left">
            Difference between actual and natural unemployment
          </td>
          <td style="text-align: left">Derived</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>avg_hourly_earnings_all</code></td>
          <td style="text-align: left">
            Average hourly earnings (private sector)
          </td>
          <td style="text-align: left">BLS (<code>CES0500000008</code>)</td>
          <td style="text-align: left">USD/hour</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>fed_funds_rate</code></td>
          <td style="text-align: left">Effective Federal Funds Rate</td>
          <td style="text-align: left">FRED (<code>FEDFUNDS</code>)</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>expected_inflation_1y</code></td>
          <td style="text-align: left">
            One-year-ahead inflation expectations
          </td>
          <td style="text-align: left">SPF</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>brent_oil_usd</code></td>
          <td style="text-align: left">Brent crude oil benchmark price</td>
          <td style="text-align: left">FRED / Kaggle</td>
          <td style="text-align: left">USD/barrel</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>natural_gas_usd</code></td>
          <td style="text-align: left">Natural gas benchmark price</td>
          <td style="text-align: left">Kaggle</td>
          <td style="text-align: left">USD/MMBtu</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>treasury_10y</code></td>
          <td style="text-align: left">
            10-Year Treasury constant maturity yield
          </td>
          <td style="text-align: left">FRED (<code>DGS10</code>)</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>treasury_6m</code></td>
          <td style="text-align: left">6-Month Treasury bill yield</td>
          <td style="text-align: left">FRED (<code>DTB6</code>)</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>is_recession</code></td>
          <td style="text-align: left">NBER recession indicator</td>
          <td style="text-align: left">FRED (<code>USREC</code>)</td>
          <td style="text-align: left">Binary (0/1)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>Export_Total</code></td>
          <td style="text-align: left">Total U.S. exports</td>
          <td style="text-align: left">Census Bureau</td>
          <td style="text-align: left">USD</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>Import_Total</code></td>
          <td style="text-align: left">Total U.S. imports</td>
          <td style="text-align: left">Census Bureau</td>
          <td style="text-align: left">USD</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>Trade_Balance</code></td>
          <td style="text-align: left">Exports minus imports</td>
          <td style="text-align: left">Derived</td>
          <td style="text-align: left">USD</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>GDPC1</code></td>
          <td style="text-align: left">Real GDP (chained 2017 dollars)</td>
          <td style="text-align: left">FRED (<code>GDPC1</code>)</td>
          <td style="text-align: left">Billions USD</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>RealGDPGrowth</code></td>
          <td style="text-align: left">Growth rate of real GDP</td>
          <td style="text-align: left">Derived</td>
          <td style="text-align: left">Percent (%)</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>DTWEXBGS</code></td>
          <td style="text-align: left">Trade-weighted U.S. dollar index</td>
          <td style="text-align: left">FRED (<code>DTWEXBGS</code>)</td>
          <td style="text-align: left">Index</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>gasoline</code></td>
          <td style="text-align: left">U.S. retail gasoline price</td>
          <td style="text-align: left">FRED (<code>GASREGW</code>)</td>
          <td style="text-align: left">USD/gallon</td>
        </tr>
        <tr>
          <td style="text-align: left"><code>10y_2y_spread</code></td>
          <td style="text-align: left">Yield curve slope (10Y − 2Y)</td>
          <td style="text-align: left">FRED (<code>T10Y2Y</code>)</td>
          <td style="text-align: left">Percentage points</td>
        </tr>
      </tbody>
    </table>
    <h2 id="data-processing-pipeline">Data Processing Pipeline</h2>
    <p>The dataset was created through a reproducible Python pipeline:</p>
    <ol type="1">
      <li>
        <strong>Load &amp; standardize</strong> CPI, Core CPI, Unemployment, and
        Earnings data.
      </li>
      <li>
        <strong>Merge</strong> all series by <code>date</code> using outer joins
        to preserve full coverage.
      </li>
      <li>
        <strong>Compute derived metrics</strong>:
        <ul>
          <li>Inflation rate (monthly, YoY)</li>
          <li>Real wage and real wage growth</li>
        </ul>
      </li>
      <li>
        <strong>Integrate additional series</strong>:
        <ul>
          <li>
            Brent oil, natural gas, Treasury rates, Fed funds, inflation
            expectations
          </li>
          <li>
            <strong>CPI components</strong>: Food, Energy, Housing, Medical, and
            Transportation indices
          </li>
        </ul>
      </li>
      <li><strong>Aggregate</strong> daily data → monthly averages.</li>
      <li>
        <strong>Trim unreliable dates</strong> (before 1957-02 and after
        2025-09).
      </li>
    </ol>
    <p>Other variables were added as needed in the project</p>
    <h1 id="eda-1">EDA</h1>
    <h2 id="phillips-curve">Phillips Curve</h2>
    <p>
      The Phillips Curve is a foundational concept in macroeconomics that
      describes an inverse relationship between inflation and unemployment.
      First introduced by A. W. Phillips in 1958, the original formulation was
      based on empirical evidence from the United Kingdom, showing that periods
      of low unemployment were typically associated with higher wage growth,
      while higher unemployment coincided with slower wage increases. Over time,
      this relationship was extended from wages to price inflation and became
      central to both economic theory and policy discussions.
    </p>
    <p>
      The initial motivation of this analysis is to empirically examine whether
      a similar dependence between inflation and unemployment can be observed in
      modern U.S. macroeconomic data. The analysis aims to assess whether
      unemployment remains a meaningful predictor of inflation and to what
      extent this traditional framework aligns with observed economic behavior.
    </p>
    <p>
      <img
        src="media/media/image1.png"
      />
    </p>
    <p>
      <img
        src="media/media/image2.png"
      />
    </p>
    <p>
      The initial empirical implementation of the classic Phillips Curve in this
      study was unsuccessful in capturing a meaningful relationship between
      inflation and labor market slack. Scatter plots of log year-over-year
      inflation against the unemployment gap exhibit no clear pattern, and the
      estimated OLS coefficient on the unemployment gap is small and
      statistically insignificant (p ≈ 0.26), with an R² close to zero.
    </p>
    <p>
      This weak performance can be explained that inflation dynamics have
      changed substantially over time due to globalization, supply-side shocks,
      and improvements in monetary policy credibility. As a result, linear
      regression based solely on unemployment cannot capture mechanisms that
      drive inflation.
    </p>
    <h2 id="augmented-phillips-curve">Augmented Phillips Curve</h2>
    <p>
      Modern macroeconomic research addresses these shortcomings through the
      Augmented Phillips Curve. This extension was developed independently by
      Friedman (1968) and Phelps (1967), who argued that any short-run trade-off
      between inflation and unemployment depends critically on whether inflation
      is anticipated.
    </p>
    <p>
      The Augmented Phillips Curve extends the classical framework by
      incorporating inflation expectations, recognizing that workers and firms
      base their decisions on anticipated future price changes. This model
      includes expected inflation (<span class="math inline"
        >\(\pi_{t}^{e}\)</span
      >) as a key determinant and is formally expressed as:
    </p>
    <p>
      <span class="math display"
        >\[\pi_{t} = \pi_{t}^{e} - \beta\left( u_{t} - u_{t}^{*} \right) +
        \epsilon_{t}\]</span
      >
    </p>
    <p>
      Here, <span class="math inline">\(\pi_{t}\)</span> is the actual inflation
      rate, <span class="math inline">\(\pi_{t}^{e}\)</span> represents expected
      inflation,
      <span class="math inline">\(\left( u_{t} - u_{t}^{*} \right)\)</span> is
      the unemployment gap (the difference between actual and the natural rate
      of unemployment), and <span class="math inline">\(\beta\)</span> measures
      the sensitivity of inflation to economic slack. This formulation implies
      that only unexpected deviations from the natural rate of unemployment
      (<span class="math inline">\(\beta &gt; 0\)</span>) affect inflation,
      capturing the concept of the Non-Accelerating Inflation Rate of
      Unemployment (NAIRU).
    </p>
    <p>
      <img
        src="media/media/image3.png"
      />
    </p>
    <p>The estimated Augmented Phillips Curve model is:</p>
    <p>
      <span class="math display"
        >\[{Inflation}_{t} = - 0.127 - 0.070{UnempGap}_{t} +
        1.197{ExpectedInflation}_{t} + \epsilon_{t}\]</span
      >
    </p>
    <p>
      The results provide strong evidence for the augmented expectations-based
      theory but only weak support for the classic unemployment-inflation
      trade-off:
    </p>
    <ul>
      <li>
        <p>
          <strong>Expected Inflation (</strong><code>expected_inflation_1y</code
          ><strong>)</strong>: The coefficient of 1.197 is highly statistically
          significant (p-value &lt; 2.2e-16). This strong, slightly
          more-than-one-for-one pass-through is the dominant driver of inflation
          in this model and is a key prediction of the augmented theory.
        </p>
      </li>
      <li>
        <p>
          <strong>Unemployment Gap (</strong><code>unemp_gap</code
          ><strong>)</strong>: The coefficient is -0.070, suggesting that a 1
          percentage point increase in the unemployment gap (higher slack) is
          associated with a 0.07 percentage point decrease in inflation. While
          the negative sign aligns with Phillips Curve theory, the relationship
          is statistically weak in the first table (p-value = 0.3063) but
          becomes significant in the second (p-value = 0.00244). The discrepancy
          in standard errors suggests potential issues with heteroskedasticity.
          Economically, this small coefficient implies the trade-off is very
          flat.
        </p>
      </li>
      <li>
        <p>
          <strong>Model Fit</strong>: The high R-squared of 0.856 indicates that
          together, the unemployment gap and expected inflation explain 85.6% of
          the variation in inflation, confirming they are key determinants.
        </p>
      </li>
    </ul>
    <p>
      <img
        src="media/media/image4.png"
      />
    </p>
    <p>
      A comparison of the classical and extended Phillips curve models
      highlights that inflation cannot be reliably modeled using labor market
      conditions alone. Inflation dynamics in the real world are shaped by a
      broader set of forces, including supply shocks, commodity price
      fluctuations, interest rate policy, exchange rate fluctuations, and global
      demand conditions. Key historical episodes visible in the data, such as
      the 1970s oil crisis, Volcker disinflation, the Great Recession, and the
      supply disruptions caused by COVID-19, exhibit inflationary fluctuations
      that unemployment alone cannot explain. The project therefore decided to
      extend the data to include additional variables, such as energy prices,
      monetary policy indicators, trade balance indicators, or financial
      conditions. By extending the model beyond the Phillips curve, the project
      can better capture the multidimensional nature of inflation and improve
      both explanatory power and forecasting accuracy.
    </p>
    <h2 id="trade-global-linkages">Trade &amp; Global Linkages</h2>
    <p>
      <img
        src="media/media/image5.png"
      />
    </p>
    <p>
      This heatmap summarizes how key global linkages interact with U.S.
      inflation dynamics. Inflation is positively correlated with oil prices,
      reflecting energy cost pass-through. GDP growth and inflation show
      moderate co-movement, while the Fed Funds Rate is positively related to
      inflation because the Federal Reserve typically raises rates during
      inflationary periods. The dollar index tends to move inversely with
      inflation: a stronger dollar reduces import prices. The trade balance
      shows negative correlations with domestic activity, weakening during
      economic expansions. These relationships highlight the external forces
      shaping U.S. inflation and justify focusing on oil, trade, and the dollar
      in the analysis.
    </p>
    <h3 id="gdp-growth">GDP Growth</h3>
    <p>We compute monthly real GDP growth as</p>
    <p>
      <span class="math display"
        >\[\text{Growth}_{t} = \left( \frac{GDPC1_{t}}{GDPC1_{t - 1}} - 1
        \right) \times 100.\]</span
      >
    </p>
    <p>
      Similarly, the <strong>year-over-year (YoY) real GDP growth</strong> —
      which compares output to the same month a year earlier — is defined as:
    </p>
    <p>
      <span class="math display"
        >\[\text{Growth}_{t}^{\text{YoY}} = \left( \frac{GDPC1_{t}}{GDPC1_{t -
        12}} - 1 \right) \times 100.\]</span
      >
    </p>
    <p>
      These measures reflect different time horizons: - The
      <strong>monthly rate</strong> captures short-term fluctuations and
      volatility. - The <strong>year-over-year rate</strong> smooths seasonal
      variation, emphasizing longer-term economic cycles.
    </p>
    <p>
      <img
        src="media/media/image6.png"
      />
    </p>
    <p>
      This chart shows monthly real GDP growth in the United States, computed
      from chained-dollar GDP (GDPC1). The series fluctuates around an average
      growth rate of approximately 0.25% per month, which corresponds to about
      3% annualized economic growth over the long run.
    </p>
    <p>
      Periods shaded in gray represent U.S. recessions. As expected, GDP growth
      typically turns negative during recessions, reflecting contractions in
      economic activity — notably during the 1973–75 Oil Crisis, 1981–82 Volcker
      Recession, 2008–09 Great Recession, and the sharp but short-lived 2020
      COVID-19 downturn.
    </p>
    <h3 id="trade-balance">Trade Balance</h3>
    <p>
      We define the trade balance as the difference between total exports and
      total imports:
    </p>
    <p>
      <span class="math display"
        >\[\text{Trade Balance}_{t} = \text{Exports}_{t} -
        \text{Imports}_{t}.\]</span
      >
    </p>
    <p>
      Positive values indicate a surplus, while negative values represent a
      deficit.
    </p>
    <p>
      <img
        src="media/media/image7.png"
      />
    </p>
    <p>
      The smoothed trends show that GDP growth and inflation move together over
      the business cycle. Inflation (red) typically rises ahead of downturns and
      falls sharply during contractions. GDP growth (teal) shows the strongest
      cyclical swings, dropping deeply during every recession.
    </p>
    <h3 id="oil-prices-and-inflation">Oil Prices and Inflation</h3>
    <p>
      Next step: analyse movements in <strong>Brent oil prices</strong> and the
      <strong>Inflation</strong> to explore how major energy price shocks relate
      to inflation dynamics. The motivation is to see whether spikes in oil
      coincide with periods of high inflation.
    </p>
    <p>
      <img
        src="media/media/image8.png"
      />
    </p>
    <p>
      This chart compares long-run movements in oil prices, inflation, and the
      U.S. trade balance using standardized 12-month rolling averages. Major
      energy shocks—such as the Gulf War, the 2008 oil spike, and the post-COVID
      supply disruptions—produce visible spikes in oil prices, which are
      followed by rises in inflation with a slight lag. At the same time, trade
      balance typically deteriorates around these episodes, reflecting higher
      import costs and disruptions to global trade. While the three series do
      not move in perfect sync, the plot highlights how oil shocks ripple
      through the economy, raising inflation and weakening external trade
      conditions.
    </p>
    <h1 id="modelling">Modelling</h1>
    <h2 id="comparing-models">Comparing models</h2>
    <p>
      <img
        src="media/media/image9.png"
      />
    </p>
    <p>
      From the plot, we observe that SARIMAX achieves the highest Adjusted R²
      (≈0.99), indicating a strong in-sample fit for inflation. The VAR model,
      by contrast, achieves a much lower Adjusted R² in its inflation equation
      (≈0.44). This is because VAR is not designed to maximize predictive
      accuracy for inflation alone. Instead, it models a full multivariate
      economic system, jointly estimating dynamic interactions among
      unemployment, wages, interest rates, energy prices, and inflation itself.
      The linear regression model performs the weakest (≈0.38 Adjusted R²). This
      is largely because linear models cannot incorporate lags, autocorrelation,
      or dynamic feedback.
    </p>
    <p>
      <img
        src="media/media/image10.png"
      />
    </p>
    <p>
      The graph shows that at short horizons (1–3 months) SARIMAX performs
      slightly better than VAR. However, as the horizon increases, SARIMAX
      exhibits a monotonic and almost linear increase in error, indicating a
      rapid accumulation of forecast uncertainty.
    </p>
    <p>
      In contrast, the VAR model exhibits stable performance at all horizons.
      The RMSE remains in a narrow range (approximately 0.5–0.7) even at long
      horizons. This indicates that VAR is more successful in modeling the
      relationship between variables that shape inflation. Since VAR captures
      how inflation responds jointly to unemployment, interest rates, wages, and
      energy prices, it can better adapt to changes in macroeconomic conditions.
    </p>
    <p>
      From a forecasting perspective, these results imply that SARIMAX is
      suitable for short-term forecasts, while VAR provides more reliable
      medium- and long-term forecasts.
    </p>
    <h2 id="strengths-of-each-modeling-approach">
      Strengths of Each Modeling Approach
    </h2>
    <p>
      <strong>SARIMAX</strong> remains the best-performing model for short-term
      inflation forecasting and for reproducing historical inflation movements.
      Its strengths include:
    </p>
    <p>
      Captures autoregressive and moving-average structure. Handles seasonality.
      Excellent in-sample fit, because it focuses strictly on inflation’s own
      past behavior. Efficient for one-step-ahead forecasts, where the
      autoregressive structure dominates.
    </p>
    <p>
      Advantages of the <strong>Linear Model</strong> Interpretability:
      Coefficients directly quantify how variables (oil, GDP, wages, rates)
      contribute to inflation. Detects structural relationships: Even without
      modeling dynamics, it highlights which predictors matter most.
    </p>
    <p>
      Even though <strong>VAR</strong> may not achieve the same level of
      predictive accuracy for inflation as SARIMAX, it remains a core tool in
      macroeconomic analysis. Its value comes from its ability to: model
      prediction for all variables; vapture feedback loops, spillovers, and
      cross-variable interactions; maintain stable forecast performance over
      long horizons, support policy simulations (e.g., how an oil shock or rate
      hike propagates through the economy), provide insights into shock
      transmission and system dynamics.
    </p>
    <h2 id="linear-regression-analysis">Linear Regression Analysis</h2>
    <h3
      id="relationship-between-oil-prices-and-inflation-using-linear-regression"
    >
      Relationship between oil prices and inflation using linear regression
    </h3>
    <p>
      This model evaluates how changes in oil prices affect monthly U.S.
      inflation. Using linear regression on lagged oil price growth, we find
      that increases in oil prices tend to raise inflation in the following
      month, reflecting the strong pass-through from energy costs to consumer
      prices.
    </p>
    <pre><code> [1] &quot;date&quot;                    &quot;cpi&quot;                    
 [3] &quot;core_cpi&quot;                &quot;inflation_rate&quot;         
 [5] &quot;core_inflation_rate&quot;     &quot;inflation_yoy&quot;          
 [7] &quot;core_inflation_yoy&quot;      &quot;log_inflation_mom&quot;      
 [9] &quot;log_inflation_yoy&quot;       &quot;expected_inflation_1y&quot;  
[11] &quot;cpi_energy&quot;              &quot;cpi_food_beverages&quot;     
[13] &quot;cpi_housing&quot;             &quot;cpi_medical&quot;            
[15] &quot;cpi_transportation&quot;      &quot;unemployment_rate&quot;      
[17] &quot;avg_hourly_earnings_all&quot; &quot;real_wage&quot;              
[19] &quot;real_wage_growth&quot;        &quot;fed_funds_rate&quot;         
[21] &quot;is_recession&quot;            &quot;unemp_noncyclical&quot;      
[23] &quot;unemp_24_54_yrs&quot;         &quot;unemp_gap&quot;              
[25] &quot;natural_gas_usd&quot;         &quot;treasury_10y&quot;           
[27] &quot;treasury_6m&quot;             &quot;GDPC1&quot;                  
[29] &quot;DTWEXBGS&quot;                &quot;brent_oil_usd&quot;          
[31] &quot;spread_10y_3m&quot;           &quot;spread_10y_6m&quot;          
[33] &quot;gasoline&quot;                &quot;trade_balance_fred&quot;     
[35] &quot;Export_Total&quot;            &quot;Import_Total&quot;           
[37] &quot;Trade_Balance&quot;           &quot;real_gdp&quot;               
[39] &quot;RealGDPGrowth&quot;           &quot;VIX&quot;                    </code></pre>
    <p>
      <img
        src="media/media/image11.png"
      />
    </p>
    <p>
      All transformed variables passed the Augmented Dickey–Fuller (ADF) test
      for stationarity. The p-values for inflation, oil price growth, trade
      balance changes, USD changes, Fed Funds Rate differences, GDP growth,
      unemployment differences, and expected inflation differences were all
      below 0.05, indicating rejection of the unit-root hypothesis. This means
      the series are stationary and appropriate for regression or time-series
      modeling.
    </p>
    <pre><code>infl_mom → best lag: 1 | corr: 0.62
oil_mom → best lag: 1 | corr: 0.494
tb_mom → best lag: 8 | corr: 0.047
usd_mom → best lag: 12 | corr: -0.312
ffr_diff → best lag: 2 | corr: 0.17
RealGDPGrowth → best lag: 8 | corr: 0.087
unemp_diff → best lag: 1 | corr: -0.037
exp_inf_diff → best lag: 2 | corr: 0.26
real_gdp → best lag: 11 | corr: -0.182
is_recession → best lag: 1 | corr: 0.063
treasury_10y → best lag: 1 | corr: 0.368
treasury_6m → best lag: 1 | corr: 0.452
spread_10y_3m → best lag: 1 | corr: -0.259
spread_10y_6m → best lag: 1 | corr: -0.258
cpi_energy → best lag: 12 | corr: -0.216
natural_gas_usd → best lag: 1 | corr: 0.125
gasoline → best lag: 12 | corr: -0.243
cpi_housing → best lag: 12 | corr: -0.379
avg_hourly_earnings_all → best lag: 12 | corr: -0.306
unemp_24_54_yrs → best lag: 1 | corr: -0.075
inflation_yoy → best lag: 1 | corr: 0.604
core_inflation_yoy → best lag: 1 | corr: 0.567
Trade_Balance → best lag: 3 | corr: -0.121
Import_Total → best lag: 1 | corr: 0.066
Export_Total → best lag: 1 | corr: 0.044
VIX → best lag: 1 | corr: -0.085</code></pre>
    <p>
      Using cross-correlation analysis, I identified the most informative lags
      for each predictor relative to monthly inflation. Oil prices showed the
      strongest relationship at a 1-month lag, while the USD index had its
      highest correlation at a 12-month lag. Other variables, such as the Fed
      Funds Rate, GDP growth, trade balance, and unemployment, showed weaker lag
      structures.
    </p>
    <h3 id="multicollinearity-diagnostics">Multicollinearity Diagnostics</h3>
    <pre><code>[1] 112449184</code></pre>
    <p>
      <img
        src="media/media/image12.png"
      />
    </p>
    <pre><code> [1] &quot;infl_mom&quot;    &quot;infl_L1&quot;     &quot;oil_mom_L1&quot;  &quot;tb_L8&quot;       &quot;ffr_L2&quot;     
 [6] &quot;gdp_L8&quot;      &quot;unemp_L1&quot;    &quot;expinf_L2&quot;   &quot;rec_L1&quot;      &quot;ngas_L1&quot;    
[11] &quot;infl_yoy_L1&quot; &quot;core_yoy_L1&quot; &quot;VIX_L1&quot;     

Call:
lm(formula = infl_mom ~ ., data = df_reg_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.0960 -0.3828  0.0036  0.4306  3.1828 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.433e-01  3.297e-01   0.435 0.664230    
date        -1.008e-05  2.296e-05  -0.439 0.661025    
infl_L1      1.919e-01  6.374e-02   3.010 0.002856 ** 
oil_mom_L1   4.499e-01  6.108e-02   7.365 2.17e-12 ***
tb_L8        8.807e-02  4.815e-02   1.829 0.068480 .  
ffr_L2      -1.001e-01  5.998e-02  -1.670 0.096148 .  
gdp_L8       1.565e-01  5.274e-02   2.968 0.003268 ** 
unemp_L1     4.727e-02  5.177e-02   0.913 0.362095    
expinf_L2    6.247e-02  5.555e-02   1.124 0.261819    
rec_L1      -1.297e-01  6.644e-02  -1.951 0.052058 .  
ngas_L1      2.347e-01  6.251e-02   3.755 0.000213 ***
infl_yoy_L1 -2.496e-01  6.996e-02  -3.568 0.000426 ***
core_yoy_L1  5.873e-02  5.644e-02   1.041 0.298989    
VIX_L1       1.740e-02  6.743e-02   0.258 0.796590    
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1

Residual standard error: 0.7855 on 269 degrees of freedom
Multiple R-squared:  0.4114,    Adjusted R-squared:  0.3829 
F-statistic: 14.46 on 13 and 269 DF,  p-value: &lt; 2.2e-16</code></pre>
    <p>
      <img
        src="media/media/image13.png"
      />
    </p>
    <pre><code>Call:
lm(formula = infl_mom ~ ., data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.0862 -0.4079  0.0320  0.4528  3.1780 

Coefficients: (1 not defined because of singularities)
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.390e-01  5.038e-01   1.070 0.285905    
date        -4.142e-05  3.745e-05  -1.106 0.270035    
infl_L1      2.033e-01  7.193e-02   2.827 0.005148 ** 
oil_mom_L1   4.457e-01  7.557e-02   5.897 1.44e-08 ***
tb_L8        8.253e-02  5.475e-02   1.507 0.133181    
ffr_L2      -1.066e-01  7.115e-02  -1.498 0.135735    
gdp_L8       1.556e-01  5.916e-02   2.631 0.009151 ** 
unemp_L1     1.884e-01  2.792e-01   0.675 0.500564    
expinf_L2    7.305e-02  6.444e-02   1.134 0.258274    
rec_L1      -1.274e-01  7.699e-02  -1.655 0.099495 .  
ngas_L1      2.526e-01  7.534e-02   3.353 0.000946 ***
infl_yoy_L1 -2.563e-01  8.073e-02  -3.175 0.001721 ** 
core_yoy_L1  3.609e-02  6.707e-02   0.538 0.591027    
VIX_L1       1.062e-02  7.988e-02   0.133 0.894379    
pred                NA         NA      NA       NA    
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1

Residual standard error: 0.8415 on 212 degrees of freedom
Multiple R-squared:  0.3914,    Adjusted R-squared:  0.3541 
F-statistic: 10.49 on 13 and 212 DF,  p-value: &lt; 2.2e-16
[1] 0.5044904
[1] 0.6433152
[1] 0.8150046</code></pre>
    <p>
      <img
        src="media/media/image14.png"
      />
    </p>
    <h3 id="best-subset-selection-using-leaps">
      Best Subset Selection (using leaps)
    </h3>
    <pre><code>[1] &quot;infl_L1&quot;     &quot;oil_mom_L1&quot;  &quot;gdp_L8&quot;      &quot;ngas_L1&quot;     &quot;infl_yoy_L1&quot;

Call:
lm(formula = best_bic_formula_clean, data = df_subset)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.4335 -0.4131  0.0282  0.4408  3.1438 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.135e-16  4.697e-02   0.000  1.00000    
infl_L1      1.718e-01  6.132e-02   2.801  0.00545 ** 
oil_mom_L1   4.724e-01  5.845e-02   8.082 1.99e-14 ***
gdp_L8       1.905e-01  4.955e-02   3.845  0.00015 ***
ngas_L1      1.860e-01  5.772e-02   3.223  0.00142 ** 
infl_yoy_L1 -1.985e-01  6.228e-02  -3.188  0.00160 ** 
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1

Residual standard error: 0.7902 on 277 degrees of freedom
Multiple R-squared:  0.3867,    Adjusted R-squared:  0.3756 
F-statistic: 34.93 on 5 and 277 DF,  p-value: &lt; 2.2e-16

Call:
lm(formula = best_adjr2_formula_clean, data = df_subset)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.1132 -0.3813 -0.0203  0.4572  3.1974 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.623e-18  4.655e-02   0.000 1.000000    
infl_L1      1.856e-01  6.242e-02   2.973 0.003214 ** 
oil_mom_L1   4.483e-01  6.041e-02   7.422 1.49e-12 ***
tb_L8        8.881e-02  4.775e-02   1.860 0.063989 .  
ffr_L2      -1.131e-01  5.813e-02  -1.946 0.052723 .  
gdp_L8       1.650e-01  5.157e-02   3.200 0.001540 ** 
expinf_L2    5.592e-02  5.450e-02   1.026 0.305752    
rec_L1      -1.140e-01  6.066e-02  -1.879 0.061352 .  
ngas_L1      2.345e-01  6.062e-02   3.868 0.000137 ***
infl_yoy_L1 -2.491e-01  6.947e-02  -3.586 0.000398 ***
core_yoy_L1  6.048e-02  5.326e-02   1.136 0.257164    
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1

Residual standard error: 0.7831 on 272 degrees of freedom
Multiple R-squared:  0.4085,    Adjusted R-squared:  0.3868 
F-statistic: 18.78 on 10 and 272 DF,  p-value: &lt; 2.2e-16
       model  k      AIC      BIC        R2    adj_R2
1       full 13 682.1438 736.8255 0.4113611 0.3829139
2   best_BIC  5 677.7579 703.2761 0.3867011 0.3756307
3 best_adjR2 10 677.5176 721.2630 0.4084965 0.3867500</code></pre>
    <p>
      <img
        src="media/media/image15.png"
      />
    </p>
    <h3 id="cross-validation-method-k-fold-method">
      Cross Validation Method K-fold method
    </h3>
    <p>
      Cross-validation confirms the same conclusion reached by the BIC-based
      subset selection: the best model for predicting inflation (infl_mom) is a
      5-variable model consisting of: infl_L1, oil_mom_L1, gdp_L8, ngas_L1,
      infl_yoy_L1.
    </p>
    <p>
      Both methods independently identify the same model size and the same
      predictors, which strongly indicates that the relationship is robust,
      stable across folds, and not driven by overfitting.
    </p>
    <h3 id="plots-how-each-variable-affects-the-economy">
      Plots how each variable affects the economy
    </h3>
    <p>
      <img
        src="media/media/image16.png"

      /><img
        src="media/media/image17.png"

      />
    </p>
    <p>
      Oil Price Change (lag 1) – Positive effect. A 1-unit increase in oil
      prices leads to about a 0.48 percentage-point increase in monthly
      inflation.
    </p>
    <p>
      GDP Growth (lag 8) – Positive effect. A 1-unit rise in GDP growth leads to
      about a 0.23 percentage-point increase in monthly inflation eight months
      later.
    </p>
    <p>
      Natural Gas Price (lag 1) – Positive effect. A 1-unit increase in natural
      gas prices raises monthly inflation by about 0.20 percentage points.
    </p>
    <p>
      Inflation (lag 1) – Positive effect. If last month’s inflation rises by 1
      percentage point, this month’s inflation increases by about 0.17
      percentage points.
    </p>
    <p>
      Year-over-year Inflation (lag 1) – Negative effect. If annual inflation
      increases by 1 percentage point, monthly inflation decreases by about 0.18
      percentage points, showing a stabilizing effect.
    </p>
    <h3 id="residuals-vs-fitted-plot-histogram-density">
      Residuals vs Fitted Plot, Histogram + Density
    </h3>
    <p>
      <img
        src="media/media/image18.png"
  
      /><img
        src="media/media/image19.png"
    
      />
    </p>
    <p>
      The linear regression model identifies clear structural drivers of
      inflation, with energy prices, GDP growth, and short-term inflation
      persistence showing the strongest effects. Residual diagnostics indicate
      that the model fits reasonably well, with residuals centered near zero and
      approximately normally distributed, though some variability remains
      unexplained.
    </p>
    <h1 id="modelling-δ-inflation---sarimax">
      Modelling Δ Inflation - SARIMAX
    </h1>
    <p>
      The modeling aims to forecast the year-over-year inflation rate using
      SARIMAX models with various economic indicators as exogenous variables.
      The focus is on selecting the best model configuration through a
      systematic grid search, variable screening, combination, and rolling
      window validation to ensure robust forecasting performance.
    </p>
    <h2 id="target-variable">Target Variable</h2>
    <p>
      The target variable is logarithmic year-over-year core CPI inflation,
      defined as:
    </p>
    <p>
      <span class="math display"
        >\[log\_ inflation\_ yoy = 100 \times ln\left( {Core\_ CPI}_{t}/{Core\_
        CPI}_{t - 12} \right)\]</span
      >
    </p>
    <p>
      The logarithmic form is preferred because it renders the growth rate
      time-additive, ensuring that the monthly change linearly sums to the
      annual change, a property that aligns directly with the linear
      differencing structure of SARIMAX models.
    </p>
    <h3 id="stationary-tests">Stationary Tests</h3>
    <pre><code>    Augmented Dickey-Fuller Test

data:  log_inflation_yoy
Dickey-Fuller = -3.0048, Lag order = 13, p-value = 0.153
alternative hypothesis: stationary

    KPSS Test for Level Stationarity

data:  log_inflation_yoy
KPSS Level = 1.7139, Truncation lag parameter = 19, p-value = 0.01</code></pre>
    <p>
      The ADF test and KPSS test both suggest that the log year-over-year
      inflation series is likely <strong>non-stationary</strong> in levels.
    </p>
    <pre><code>    Augmented Dickey-Fuller Test

data:  d_log_inflation_yoy
Dickey-Fuller = -6.741, Lag order = 13, p-value = 0.01
alternative hypothesis: stationary

    KPSS Test for Level Stationarity

data:  d_log_inflation_yoy
KPSS Level = 0.032617, Truncation lag parameter = 19, p-value = 0.1</code></pre>
    <p>
      The both tests suggest that the differenced log year-over-year inflation
      series is likely <strong>stationary</strong>.
    </p>
    <h3 id="autocorrelation">Autocorrelation</h3>
    <p>
      <img
        src="media/media/image20.png"

      />
    </p>
    <p>
      <strong>Non-Seasonal Orders</strong> The PACF decays after lag 1 (.42),
      lag 2 (.181). That suggests <strong>p = 1 or 2</strong> for an AR
      component. The ACF decays after lag 1 (.42) lag 2 (.325), and lag 3
      (.121), suggesting <strong>q = 2 or 3</strong> for an MA component.
    </p>
    <p>
      <strong>Seasonal Orders</strong> The ACF has a negative peak at lag 12
      (-.367), and the PACF has a negative peak at lag 12 (-.433), a smaller one
      at lag 24 (-.237) and lag 36 (-.215), indicating a medium or weak seasonal
      pattern. This suggests <strong>P = 1 or 2</strong> for a seasonal AR
      component, and <strong>Q = 1 or 2</strong> for a seasonal MA component,
      with <strong>s = 12</strong>. Because seasonal lags (12, 24, 36) decay
      quickly in ACF, we choose <strong>D = 0</strong>.
    </p>
    <p>
      Thus, the <strong>potential SARIMA orders</strong> are: p &lt;= 1, d = 1,
      q &lt;= 3, P &lt;= 2, D = 0, Q &lt;= 2, s = 12.
    </p>
    <h2 id="trend-and-seasonality-decomposition">
      Trend and seasonality decomposition
    </h2>
    <p>
      <img
        src="media/media/image21.png"

      />
    </p>
    <p>
      The STL decomposition reveals that the log year-over-year inflation is
      dominated by a long-term trend and exhibits minimal seasonality. The trend
      smooths the long-term movement, confirming persistent structural changes.
      The seasonal component, although repeating every 12 months, displays a
      very narrow amplitude (around ±0.006), indicating that seasonality
      contributes negligibly. Meanwhile, the remainder component shows
      volatility clustering in specific periods, which are connected to Oil
      Crisis, Energy Shock, and COVID-19, but otherwise oscillates around zero.
    </p>
    <p>
      The high volatility clustering and large swings in log year-over-year
      inflation suggest potential structural breaks or regime shifts over the
      sample period.
    </p>
    <h2 id="structural-breaks-or-regime-shifts">
      Structural breaks or regime shifts
    </h2>
    <pre><code>    Chow test

data:  x_ts ~ 1
F = 388.17, p-value &lt; 2.2e-16</code></pre>
    <p>
      <img
        src="media/media/image22.png"

      />
    </p>
    <p>
      The Chow Test result F = 6.6481, p-value = 2.2e-16 strongly suggests the
      presence of structural breaks. The break-point analysis gets the lowest
      BIC (2426) occurs at m = 4, indicating four structural breaks.
    </p>
    <p>
      <img
        src="media/media/image23.png"
      />
    </p>
    <p>
      The largest structrural break occurs around early 1980s, coinciding with
      the Volcker disinflation period. Since ARIMA models assume the same
      variance and mean over time, we
      <strong>cut out the data before the break (1984-01-01)</strong> to
      simplify modeling.
    </p>
    <p>
      Advanced models (like <strong>Markov-Switching AR</strong>) allow
      parameters to change over time. This would let us keep the old data, but
      it is much more complex to implement than ARIMA and is not involved in the
      study.
    </p>
    <h2 id="x-exogenous-variables">X Exogenous Variables</h2>
    <p>The X variables considered are:</p>
    <table style="width: 97%">
      <colgroup>
        <col style="width: 36%" />
        <col style="width: 30%" />
        <col style="width: 30%" />
      </colgroup>
      <tbody>
        <tr>
          <td style="text-align: left"><strong>Variable Name</strong></td>
          <td style="text-align: left"><strong>Description</strong></td>
          <td style="text-align: left"><strong>Need Differencing?</strong></td>
        </tr>
        <tr>
          <td style="text-align: left"><code>expected_inflation_1y</code></td>
          <td style="text-align: left">
            Expected average inflation over the next 12 months.
          </td>
          <td style="text-align: left"><strong>Yes</strong></td>
        </tr>
        <tr>
          <td style="text-align: left"><code>unemp_gap</code></td>
          <td style="text-align: left">Unemployment gap.</td>
          <td style="text-align: left"><strong>Yes</strong></td>
        </tr>
        <tr>
          <td style="text-align: left">
            <code>trade_balance_singed_log</code>
          </td>
          <td style="text-align: left">Trade Balance Symmetric Logarithm</td>
          <td style="text-align: left"><strong>Yes</strong></td>
        </tr>
        <tr>
          <td style="text-align: left"><code>RealGDPGrowth</code></td>
          <td style="text-align: left">Real GDP growth rate.</td>
          <td style="text-align: left"><strong>No</strong></td>
        </tr>
        <tr>
          <td style="text-align: left"><code>spread_10y_3m</code></td>
          <td style="text-align: left">
            Yield spread between 10-year and 3-month Treasury securities.
          </td>
          <td style="text-align: left"><strong>No</strong></td>
        </tr>
        <tr>
          <td style="text-align: left"><code>gasoline</code></td>
          <td style="text-align: left">Gasoline prices.</td>
          <td style="text-align: left"><strong>Yes</strong></td>
        </tr>
        <tr>
          <td style="text-align: left"><code>fed_funds_rate</code></td>
          <td style="text-align: left">Effective Federal Funds Rate.</td>
          <td style="text-align: left"><strong>Yes</strong></td>
        </tr>
      </tbody>
    </table>
    <p>
      Stationary tests (ADF and KPSS) suggest that five of the variables need
      differencing to achieve stationarity, while two (Real GDP Growth and Yield
      Spread) are already stationary in levels.
    </p>
    <pre><code>=== Stationarity Test Criteria ===
ADF Test (Null: Non-stationary): p-value &lt; 0.05 → Stationary
KPSS Test (Null: Stationary): p-value &gt; 0.05 → Stationary
==================================

Testing: expected_inflation_1y 
  Result: expected_inflation_1y is non-stationary 
  ADF p-value = 0.1235 (Non-stationary) 
  KPSS p-value = 0.01 (Non-stationary) 

Testing: d_expected_inflation_1y 
  Result: d_expected_inflation_1y is stationary 
  ADF p-value = 0.01 (Stationary) 
  KPSS p-value = 0.1 (Stationary) 

Testing: unemp_gap 
  Result: unemp_gap is stationary 
  ADF p-value = 0.0294 (Stationary) 
  KPSS p-value = 0.1 (Stationary) 

Testing: d_unemp_gap 
  Result: d_unemp_gap is stationary 
  ADF p-value = 0.01 (Stationary) 
  KPSS p-value = 0.1 (Stationary) 

Testing: TB_signed_log 
  Result: TB_signed_log is inconclusive (conflicting results) 
  ADF p-value = 0.018 (Stationary) 
  KPSS p-value = 0.01 (Non-stationary) 

Testing: d_TB_signed_log 
  Result: d_TB_signed_log is stationary 
  ADF p-value = 0.01 (Stationary) 
  KPSS p-value = 0.1 (Stationary) 

Testing: RealGDPGrowth 
  Result: RealGDPGrowth is stationary 
  ADF p-value = 0.01 (Stationary) 
  KPSS p-value = 0.1 (Stationary) 

Testing: d_RealGDPGrowth 
  Result: d_RealGDPGrowth is stationary 
  ADF p-value = 0.01 (Stationary) 
  KPSS p-value = 0.1 (Stationary) 

Testing: spread_10y_3m 
  Result: spread_10y_3m is stationary 
  ADF p-value = 0.01 (Stationary) 
  KPSS p-value = 0.1 (Stationary) 

Testing: d_spread_10y_3m 
  Result: d_spread_10y_3m is stationary 
  ADF p-value = 0.01 (Stationary) 
  KPSS p-value = 0.1 (Stationary) 

Testing: gasoline 
  Result: gasoline is non-stationary 
  ADF p-value = 0.1028 (Non-stationary) 
  KPSS p-value = 0.01 (Non-stationary) 

Testing: d_gasoline 
  Result: d_gasoline is stationary 
  ADF p-value = 0.01 (Stationary) 
  KPSS p-value = 0.1 (Stationary) 

Testing: fed_funds_rate 
  Result: fed_funds_rate is inconclusive (conflicting results) 
  ADF p-value = 0.0252 (Stationary) 
  KPSS p-value = 0.01 (Non-stationary) 

Testing: d_fed_funds_rate 
  Result: d_fed_funds_rate is stationary 
  ADF p-value = 0.01 (Stationary) 
  KPSS p-value = 0.1 (Stationary) </code></pre>
    <h2 id="model-selection">Model Selection</h2>
    <h3 id="metrics">Metrics</h3>
    <ol start="7" type="1">
      <li>
        <strong>MASE</strong> (Mean Absolute Scaled Error) is chosen as the
        primary evaluation metric for model selection due to its
        scale-independence and interpretability. MASE compares the forecast
        accuracy of a model against a naive benchmark, making it suitable for
        comparing models across different datasets and scales.
      </li>
    </ol>
    <p>
      <span class="math display"
        >\[\text{MASE} = \frac{\frac{1}{h}\sum_{t = 1}^{h}\left| Y_{t} -
        {\widehat{Y}}_{t} \right|}{\frac{1}{n - 1}\sum_{i = 2}^{n}\left| Y_{i} -
        Y_{i - 1} \right|}\]</span
      >
    </p>
    <p>Where:</p>
    <ul>
      <li>
        <p>
          <span class="math inline">\(Y_{t}\)</span>: Actual value in the test
          set.
        </p>
      </li>
      <li>
        <p>
          <span class="math inline">\({\widehat{Y}}_{t}\)</span>: Forecasted
          value in the test set.
        </p>
      </li>
      <li>
        <p>
          <span class="math inline">\(h\)</span>: Number of steps in the
          forecast horizon (test set size).
        </p>
      </li>
      <li>
        <p>
          <span class="math inline">\(n\)</span>: Number of observations in the
          training set.
        </p>
      </li>
      <li>
        <p>
          <span class="math inline">\(Y_{i} - Y_{i - 1}\)</span>: The error of a
          naive forecast.
        </p>
      </li>
    </ul>
    <p>
      We implemented a custom calculation for the Mean Absolute Scaled Error
      (MASE). The standard <code>accuracy(``)</code> implementation in the R
      <code>forecast</code> package detects the seasonal frequency (12) of the
      data and defaults to a <strong>seasonal naive benchmark</strong>. We
      determined this to be unsuitable in this context because the STL
      decomposition reveals a very weak seasonal effect. Consequently, we
      computed MASE manually using the in-sample mean absolute error of a
      <strong>simple</strong> random walk (Lag-1) as the denominator.
    </p>
    <ol start="2" type="1">
      <li>
        <strong>Theil’s U Statistic</strong> complements MASE by providing a
        relative measure of forecast accuracy. A Theil’s U value less than 1
        indicates that the model outperforms a naive forecast, while a value
        greater than 1 suggests inferior performance.
      </li>
    </ol>
    <p>
      <span class="math display"
        >\[U = \sqrt{\frac{\sum_{t = 1}^{h}\left( Y_{t} - {\widehat{Y}}_{t}
        \right)^{2}}{\sum_{t = 1}^{h}\left( Y_{t} - Y_{t - 1}
        \right)^{2}}}\]</span
      >
    </p>
    <h3 id="criteria-for-model-selection">Criteria for Model Selection</h3>
    <p>
      The model selection process follows these criteria for an academic
      setting:
    </p>
    <ol start="8" type="1">
      <li>
        <p>
          <strong>Statistical Validity</strong>: Models must pass the Ljung-Box
          test for residual autocorrelation (p-value &gt; 0.05) to ensure that
          residuals behave like white noise.
        </p>
      </li>
      <li>
        <p>
          <strong>ARIMA Parameter Validity</strong>: All autoregressive (AR) and
          moving average (MA) coefficients must be statistically significant
          (p-value &lt; 0.05). Additionally, all parameter estimates must have
          valid standard errors (no NA values) to ensure mathematically
          stablility.
        </p>
      </li>
      <li>
        <p>
          <strong>Exogenous Coefficient Significance</strong>: All exogenous
          variable coefficients must be statistically significant (p-value &lt;
          0.05) to ensure that included predictors contribute meaningfully to
          the model.
        </p>
      </li>
      <li>
        <p>
          <strong>Primary Ranking</strong>: Among statistically valid models,
          the optimal model is selected based on the lowest Mean Absolute Scaled
          Error (MASE) on the validation/test set.
        </p>
      </li>
      <li>
        <p>
          <strong>Benchmark Superiority</strong>: Candidate models must achieve
          a Theil’s U &lt; 1, confirming they outperform the naive random walk
          benchmark.
        </p>
      </li>
      <li>
        <p>
          <strong>Model Parsimony</strong>: Among models that meet the above
          criteria, preference is given to those with fewer parameters to avoid
          overfitting and enhance interpretability.
        </p>
      </li>
    </ol>
    <h3 id="rolling-window-validation-setup">
      Rolling Window Validation Setup
    </h3>
    <p>
      We employed an expanding window cross-validation approach. All training
      windows are anchored at the series start date (1984-01-01). The initial
      training window extends to 2010-01-01, comprising 27 years (324 months) of
      data, while the final window extends to 2018-12-01. This results in a
      total of 108 validation folds.
    </p>
    <p>
      For each iteration, the model is trained on the current window to generate
      a 12-step-ahead forecast. Test MASE and Theil’s U are computed for each
      forecast horizon and then averaged across all 108 folds to derive the
      overall performance metrics.
    </p>
    <h3 id="forward-stepwise-selection-with-rolling-validation">
      Forward Stepwise Selection with Rolling Validation
    </h3>
    <pre><code>Total Model Specifications to Evaluate: 8746920 , populated via (p * q * P * Q) * choose( 7 x candidates * max lags, max 3 legs to combine)</code></pre>
    <p>
      The model selection process employs a forward stepwise selection strategy
      combined with rolling window validation to systematically evaluate a vast
      array of SARIMAX model specifications.
    </p>
    <h4 id="baseline-specification-univariate">
      1. Baseline Specification (Univariate)
    </h4>
    <p>
      We established a baseline for the univariate analysis by performing a grid
      search for optimal SARIMA<span class="math inline"
        >\((p,d,q)(P,D,Q)\)</span
      >
      parameters. To ensure statistical validity, we excluded any models that
      failed the Ljung-Box test, exhibited invalid (NA) standard errors, or
      contained statistically insignificant coefficients (<span
        class="math inline"
        >\(p &gt; 0.10\)</span
      >). The remaining candidates were then ranked based on the Mean Absolute
      Scaled Error (MASE) derived from the rolling window validation, with the
      top-performing models advancing to the multivariate phase.
    </p>
    <p>
      To mitigate the high computational cost of a full rolling validation at
      this preliminary stage, we employed a
      <strong>strided validation strategy</strong> with a
      <strong>step size of 11 months</strong>. Since 11 is coprime to the
      seasonal period (12), this interval ensures that the validation origins
      rotate through calendar months, preventing seasonal bias, while
      significantly reducing the computational burden.
    </p>
    <p>
      We develop a function <code>grid_search_sarimax_3``()</code> that performs
      a grid search over specified SARIMA orders and exogenous variable
      configurations, utilizing rolling window validation with a defined step
      size.
    </p>
    <table style="width: 98%">
      <caption>
        Good Baseline Models after Filtering
      </caption>
      <colgroup>
        <col style="width: 31%" />
        <col style="width: 13%" />
        <col style="width: 10%" />
        <col style="width: 13%" />
        <col style="width: 28%" />
      </colgroup>
      <thead>
        <tr>
          <th style="text-align: left">model_name</th>
          <th style="text-align: right">Test_MASE</th>
          <th style="text-align: right">Theil_U</th>
          <th style="text-align: right">Ljung_Box</th>
          <th style="text-align: right">Largest_No_Xreg_p_value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="text-align: left">SARIMA(1,1,1)(0,1,2)[12]</td>
          <td style="text-align: right">2.204</td>
          <td style="text-align: right">0.968</td>
          <td style="text-align: right">0.614</td>
          <td style="text-align: right">0.000</td>
        </tr>
        <tr>
          <td style="text-align: left">SARIMA(1,1,1)(0,0,2)[12]</td>
          <td style="text-align: right">2.232</td>
          <td style="text-align: right">1.057</td>
          <td style="text-align: right">0.321</td>
          <td style="text-align: right">0.016</td>
        </tr>
        <tr>
          <td style="text-align: left">SARIMA(1,1,1)(1,0,1)[12]</td>
          <td style="text-align: right">2.256</td>
          <td style="text-align: right">1.074</td>
          <td style="text-align: right">0.313</td>
          <td style="text-align: right">0.017</td>
        </tr>
        <tr>
          <td style="text-align: left">SARIMA(2,1,2)(1,0,2)[12]</td>
          <td style="text-align: right">2.267</td>
          <td style="text-align: right">1.014</td>
          <td style="text-align: right">0.356</td>
          <td style="text-align: right">0.001</td>
        </tr>
        <tr>
          <td style="text-align: left">SARIMA(1,1,1)(0,0,1)[12]</td>
          <td style="text-align: right">2.286</td>
          <td style="text-align: right">1.012</td>
          <td style="text-align: right">0.364</td>
          <td style="text-align: right">0.000</td>
        </tr>
        <tr>
          <td style="text-align: left">SARIMA(2,1,2)(1,0,1)[12]</td>
          <td style="text-align: right">2.369</td>
          <td style="text-align: right">1.164</td>
          <td style="text-align: right">0.295</td>
          <td style="text-align: right">0.006</td>
        </tr>
      </tbody>
    </table>
    <h4 id="exogenous-variable-screening-bivariate">
      2. Exogenous Variable Screening (Bivariate)
    </h4>
    <p>
      We conducted a bivariate screening for each exogenous candidate across all
      successful baseline specifications. Each lag of every exogenous variable
      (<span class="math inline">\(X_{t - k},k = 0..12\)</span>) was
      individually tested against the baseline residuals. We retained only those
      variable-lag pairs that demonstrated statistical significance (<span
        class="math inline"
        >\(p &lt; 0.1\)</span
      >). Subsequently, these candidates were incorporated into the baseline
      model to verify their significance within the full training and validation
      datasets.Validated variable-lag pairs were then compiled into a master
      list for each baseline model to inform subsequent multivariate
      specification searches. To constrain the search space, we retained only
      the <strong>top two</strong> most significant lags per variable-baseline
      specification.
    </p>
    <pre><code>In total, 24 variable-lag pairs across 9 baseline Specifications pass the screening. Here are three examples.</code></pre>
    <table style="width: 97%">
      <caption>
        Three examples that pass the screening
      </caption>
      <colgroup>
        <col style="width: 36%" />
        <col style="width: 23%" />
        <col style="width: 7%" />
        <col style="width: 12%" />
        <col style="width: 17%" />
      </colgroup>
      <thead>
        <tr>
          <th style="text-align: left">baseline_model</th>
          <th style="text-align: left">variable</th>
          <th style="text-align: right">lag</th>
          <th style="text-align: right">p_value</th>
          <th style="text-align: right">coefficient</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="text-align: left">SARIMA(1,1,1)(0,0,1)[12]</td>
          <td style="text-align: left">d_fed_funds_rate</td>
          <td style="text-align: right">0</td>
          <td style="text-align: right">0.014</td>
          <td style="text-align: right">0.019</td>
        </tr>
        <tr>
          <td style="text-align: left">SARIMA(1,1,1)(0,0,1)[12]</td>
          <td style="text-align: left">d_fed_funds_rate</td>
          <td style="text-align: right">3</td>
          <td style="text-align: right">0.042</td>
          <td style="text-align: right">0.016</td>
        </tr>
        <tr>
          <td style="text-align: left">SARIMA(1,1,1)(0,0,2)[12]</td>
          <td style="text-align: left">d_fed_funds_rate</td>
          <td style="text-align: right">0</td>
          <td style="text-align: right">0.004</td>
          <td style="text-align: right">0.019</td>
        </tr>
      </tbody>
    </table>
    <h4 id="multivariate-permutation-search">
      3. Multivariate Permutation Search
    </h4>
    <p>
      We performed a multivariate expansion by incorporating the significant
      variable-lag pairs identified during the screening phase. To control for
      complexity, we limited each specification to a maximum of three exogenous
      terms. We evaluated each combination for coefficient significance (<span
        class="math inline"
        >\(p &lt; 0.1\)</span
      >). Specifications that passed this test underwent rolling window
      validation (step size = 11) to benchmark forecasting performance against
      the baseline. Only the specifications which pass all criteria are kept.
      Finally, the competing models were ranked by MASE, and the top five are
      moved to the final validation phase.
    </p>
    <table style="width: 98%">
      <caption>
        Top 5 Winners after Combination Search
      </caption>
      <colgroup>
        <col style="width: 55%" />
        <col style="width: 6%" />
        <col style="width: 6%" />
        <col style="width: 10%" />
        <col style="width: 9%" />
        <col style="width: 10%" />
      </colgroup>
      <thead>
        <tr>
          <th style="text-align: left">Model Name</th>
          <th style="text-align: right">Test MASE</th>
          <th>Theil U</th>
          <th style="text-align: right">Ljung-Box p-val</th>
          <th style="text-align: right">Largest X Reg p-value</th>
          <th style="text-align: right">Largest Non-Reg p-value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="text-align: left">
            SARIMA(1,1,1)(1,0,2)[12]+d_unemp_gap_l11
          </td>
          <td style="text-align: right">1.436</td>
          <td>0.815</td>
          <td style="text-align: right">0.476</td>
          <td style="text-align: right">0.079</td>
          <td style="text-align: right">0.000</td>
        </tr>
        <tr>
          <td style="text-align: left">
            SARIMA(1,1,1)(1,0,2)[12]+d_unemp_gap_l11+spread_10y_3m_l0
          </td>
          <td style="text-align: right">1.635</td>
          <td>1.010</td>
          <td style="text-align: right">0.467</td>
          <td style="text-align: right">0.075</td>
          <td style="text-align: right">0.000</td>
        </tr>
        <tr>
          <td style="text-align: left">
            SARIMA(1,1,1)(0,0,2)[12]+d_fed_funds_rate_l3
          </td>
          <td style="text-align: right">1.808</td>
          <td>0.785</td>
          <td style="text-align: right">0.292</td>
          <td style="text-align: right">0.021</td>
          <td style="text-align: right">0.009</td>
        </tr>
        <tr>
          <td style="text-align: left">
            SARIMA(1,1,1)(1,0,1)[12]+d_fed_funds_rate_l3
          </td>
          <td style="text-align: right">1.851</td>
          <td>0.798</td>
          <td style="text-align: right">0.262</td>
          <td style="text-align: right">0.028</td>
          <td style="text-align: right">0.011</td>
        </tr>
        <tr>
          <td style="text-align: left">
            SARIMA(1,1,1)(1,0,2)[12]+d_fed_funds_rate_l3+spread_10y_3m_l0
          </td>
          <td style="text-align: right">1.901</td>
          <td>0.921</td>
          <td style="text-align: right">0.333</td>
          <td style="text-align: right">0.027</td>
          <td style="text-align: right">0.000</td>
        </tr>
      </tbody>
    </table>
    <h4 id="final-validation">4. Final Validation</h4>
    <p>
      We perform a full rolling windows validation on the final candidates,
      followed by a manual selection of the optimal model.
    </p>
    <table style="width: 98%">
      <caption>
        Rolling Validation Summary
      </caption>
      <colgroup>
        <col style="width: 56%" />
        <col style="width: 6%" />
        <col style="width: 6%" />
        <col style="width: 6%" />
        <col style="width: 10%" />
        <col style="width: 10%" />
      </colgroup>
      <thead>
        <tr>
          <th style="text-align: left">Model Name</th>
          <th style="text-align: right">Test MASE</th>
          <th>Theil U</th>
          <th style="text-align: right">Test MASE SD</th>
          <th style="text-align: right">Ljung-Box p-val</th>
          <th style="text-align: right">Largest X Reg p-value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="text-align: left">
            SARIMA(1,1,1)(1,0,2)[12]+d_unemp_gap_l11
          </td>
          <td style="text-align: right">1.873</td>
          <td>0.997</td>
          <td style="text-align: right">1.368</td>
          <td style="text-align: right">0.476</td>
          <td style="text-align: right">0.079</td>
        </tr>
        <tr>
          <td style="text-align: left">
            SARIMA(1,1,1)(0,0,2)[12]+d_fed_funds_rate_l3
          </td>
          <td style="text-align: right">1.935</td>
          <td>0.982</td>
          <td style="text-align: right">1.304</td>
          <td style="text-align: right">0.292</td>
          <td style="text-align: right">0.021</td>
        </tr>
        <tr>
          <td style="text-align: left">
            SARIMA(1,1,1)(1,0,1)[12]+d_fed_funds_rate_l3
          </td>
          <td style="text-align: right">1.955</td>
          <td>0.980</td>
          <td style="text-align: right">1.328</td>
          <td style="text-align: right">0.262</td>
          <td style="text-align: right">0.028</td>
        </tr>
        <tr>
          <td style="text-align: left">
            SARIMA(1,1,1)(1,0,2)[12]+d_unemp_gap_l11+spread_10y_3m_l0
          </td>
          <td style="text-align: right">1.975</td>
          <td>1.127</td>
          <td style="text-align: right">1.379</td>
          <td style="text-align: right">0.467</td>
          <td style="text-align: right">0.075</td>
        </tr>
        <tr>
          <td style="text-align: left">
            SARIMA(1,1,1)(1,0,2)[12]+d_fed_funds_rate_l3+spread_10y_3m_l0
          </td>
          <td style="text-align: right">2.036</td>
          <td>1.112</td>
          <td style="text-align: right">1.372</td>
          <td style="text-align: right">0.333</td>
          <td style="text-align: right">0.027</td>
        </tr>
      </tbody>
    </table>
    <p>
      <img
        src="media/media/image24.png"

      />
    </p>
    <p>
      <img
        src="media/media/image25.png"
   
      />
    </p>
    <p>
      The top three specifications from the rolling validation exhibited
      comparable Test MASE scores up to the seventh forecast horizon, after
      which they began to diverge. However, since the Theil’s U statistic for
      even the best model exceeded 1.0 beyond the 3rd horizon, performance
      differences after the seventh horizon are inconsequential.
    </p>
    <p>
      Although the top-ranked model, SARIMA(1,1,1)(1,0,2)[12]+d_unemp_gap_l11,
      minimized the error, its exogenous regressor was only marginally
      significant (<span class="math inline">\(p = 0.079\)</span>).
      Consequently, we selected the second-best model,
      SARIMA(1,1,1)(0,0,2)[12]+d_fed_funds_rate_l3, which all coefficients are
      significant, as the final specification for diagnostics and forecasting.
    </p>
    <h2 id="final-model-diagnostics">Final Model Diagnostics</h2>
    <p>
      The winner is SARIMA(1,1,1)(0,0,2)[12] augmented with d_fed_funds_rate at
      lag 3.
    </p>
    <h3 id="model-summary">Model Summary</h3>
    <pre><code>--- Model Summary ---
Series: ts(model_data$y, frequency = frequency) 
Regression with ARIMA(1,1,1)(0,0,2)[12] errors 

Coefficients:
         ar1      ma1     sma1    sma2  d_fed_funds_rate_l3
      0.9991  -0.8701  -1.1470  0.1479               0.0154
s.e.  0.0035   0.0227   0.0941  0.0568               0.0067

sigma^2 = 0.007258:  log likelihood = 427.65
AIC=-843.31   AICc=-843.11   BIC=-818.95

Training set error measures:
                       ME      RMSE        MAE        MPE     MAPE      MASE
Training set -0.005416098 0.0845948 0.06578378 -0.2182392 2.720714 0.1513679
                    ACF1
Training set -0.02255177

z test of coefficients:

                      Estimate Std. Error  z value  Pr(&gt;|z|)    
ar1                  0.9990817  0.0034847 286.7088 &lt; 2.2e-16 ***
ma1                 -0.8700675  0.0226644 -38.3892 &lt; 2.2e-16 ***
sma1                -1.1469594  0.0941232 -12.1857 &lt; 2.2e-16 ***
sma2                 0.1479033  0.0568454   2.6019  0.009272 ** 
d_fed_funds_rate_l3  0.0154304  0.0066674   2.3143  0.020651 *  
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
    <p>
      All coefficients are statistically significant at the 5% level. The AR(1)
      coefficient is .999 (p &lt; .001), indicating very strong persistence in
      the differenced series.
    </p>
    <h3 id="residuals-checks">Residuals Checks</h3>
    <p>
      <img
        src="media/media/image26.png"

      />
    </p>
    <pre><code>    Ljung-Box test

data:  Residuals from Regression with ARIMA(1,1,1)(0,0,2)[12] errors
Q* = 21.837, df = 20, p-value = 0.3494

Model df: 4.   Total lags used: 24</code></pre>
    <p>
      There are minor spikes around lag 6 and 8 that touch the significance
      threshold. Also, there is a noticeable negative spike at Lag 36. However,
      the Ljung-Box Test returns a p-value of 0.3494 (<span class="math inline"
        >\(Q^{*} = 21.837\)</span
      >, <span class="math inline">\(df = 20\)</span>), confirming that the
      residuals are independently distributed (white noise) and the model does
      not suffer from significant lack of fit.
    </p>
    <p>
      <img
        src="media/media/image27.png"
      
      />
    </p>
    <p>
      Both the histogram of residuals and the Normal Q-Q Plot confirm that the
      residuals follow an approximate normal distribution, with some deviation
      when examining the extreme tails.
    </p>
    <h3 id="in-sample-fit-performance">In-Sample Fit Performance</h3>
    <p>
      <img
        src="media/media/image28.png"
       
      />
    </p>
    <p>
      The robust in-sample fit (Adj R² = 0.99) indicates that the model explains
      a substantial portion of the variance in inflation based on
      <strong>one-step-ahead</strong> fitted values.
    </p>
    <h2 id="forecasting-performance">Forecasting Performance</h2>
    <h3 id="forecast-in-validation-dataset">Forecast In Validation Dataset</h3>
    <p>
      <img
        src="media/media/image29.png"
      />
    </p>
    <p>
      The forecast
      <strong>performance is degraded when horizon increases</strong>. The 1st
      horizon is near perfect; the 2nd and 3rd is good; from the 4th, the
      performance deteriorates rapidly from the fourth horizon onward.
    </p>
    <p>
      This degradation is driven by <strong>error propagation</strong>, where
      deviations from previous steps are carried forward and compounded. This
      behavior is primarily attributable to the highly persistent AR(1)
      component (<span class="math inline">\(0.999\)</span>), which causes
      shocks to have a permanent effect on the forecast trajectory.
      Additionally, the corrective power of the MA(1) component (<span
        class="math inline"
        >\(- 0.887\)</span
      >) is limited to the first horizon. Beyond
      <span class="math inline">\(h = 1\)</span>, the model lacks the observed
      target values necessary to calculate true residuals, causing the moving
      average term to effectively vanish.
    </p>
    <p>
      Therefore, while the model fits the data mathematically, its ability to
      anticipate turning points is limited by this persistence.
    </p>
    <p>
      <img
        src="media/media/image30.png"
      />
    </p>
    <p>
      The plot confirms that error propagation intensifies as the horizon
      increases, resulting in a <strong>phase shift</strong> at higher horizons.
      Specifically, at <span class="math inline">\(h = 12\)</span>, the forecast
      trajectory appears to simply replicate the historical data with a delay.
    </p>
    <p>
      The statistically significant SMA(1) coefficient (-1.15) contributes to
      the observed phase shift by reinforcing the replication of past seasonal
      dynamics in the forecast trajectory.
    </p>
    <h3 id="forecast-in-the-test-dataset">Forecast in the Test Dataset</h3>
    <pre><code>[1] &quot;Running Test Rolling Forecast from 2020-01-01 to 2025-08-01&quot;</code></pre>
    <p>
      <img
        src="media/media/image31.png"
      />
    </p>
    <p>
      The plot confirms accuracy decay over increasing horizons, and error
      propagation is evident.
    </p>
    <p>
      <img
        src="media/media/image32.png"
      />
    </p>
    <p>
      The error propagation and phase shift pattern is consistent with the
      validation set results. However, the overall accuracy is noticeably worse
      across all horizons. A significant portion of the forecast error is
      attributable to the extreme volatility observed during the 2021–2022
      period, where the model struggled to capture the rapid acceleration of
      inflation.
    </p>
    <h3 id="compare-validation-vs-test-horizons">
      Compare Validation vs Test Horizons
    </h3>
    <p>
      <img
        src="media/media/image33.png"
      />
    </p>
    <ol start="14" type="1">
      <li>
        <p>
          The widening gap between the two curves highlights a significant
          degradation in model performance, likely attributable to the
          structural regime shift between the pre-COVID and post-COVID economic
          environments.
        </p>
      </li>
      <li>
        <p>
          Both two lines are near linear, indicating the forecast error
          accumulates linearly,leading to significantly wider confidence
          intervals at the 12-month horizon compared to the 1-month horizon.
        </p>
      </li>
    </ol>
    <h3 id="forecast-the-future-horizons">Forecast the Future Horizons</h3>
    <p>To enable forecasting for the future, we assume three scenarios:</p>
    <ol type="1">
      <li><p>The Fed fund rate keeps unchanged in the future.</p></li>
      <li>
        <p>It gets a cut of 2% in the next month, then stays unchanged.</p>
      </li>
      <li>
        <p>It gets a hike of 2% in the next month, then stays unchanged.</p>
      </li>
    </ol>
    <p>
      <img
        src="media/media/image34.png"
      />
    </p>
    <ul>
      <li>
        <p>
          The three lines converges during the first three months, reflecting
          the three-month lag of the fed funds rate impact on inflation.
        </p>
      </li>
      <li>
        <p>
          At month four, the higher the fed funds rate, the lower the inflation,
          which is consistent with economic theory.
        </p>
      </li>
      <li>
        <p>
          Inflation converges again after month six. This occurs because the fed
          funds rate shocks are one-time pulses, and their effects dissipate
          over time due to the lag structure.
        </p>
      </li>
      <li>
        <p>
          The confidence levels (shaded area) around the “Hold Rates” scenario
          indicate the uncertainty of the forecast, that widening over time.
        </p>
      </li>
    </ul>
    <h1 id="macroeconomic-system-analysis-a-var-approach">
      Macroeconomic System Analysis: A VAR Approach
    </h1>
    <h2 id="introduction-1">Introduction</h2>
    <p>
      In modern macroeconomic analysis, understanding how monetary policy (such
      as the federal funds rate), inflation, unemployment, and external supply
      shocks (e.g., oil prices) interact with each other is essential. This
      project uses a Vector Autoregression (VAR) model to build a multivariate
      time-series framework that can quantify and predict the dynamic
      relationships among key economic indicators. Specifically, we focus on the
      federal funds rate, unemployment rate, inflation rate, Brent crude oil
      price, and real wages.
    </p>
    <p>The main objectives of this study are:</p>
    <p>
      To identify statistically significant predictive relationships using
      Granger causality tests.
    </p>
    <p>
      To analyze how shocks—such as interest-rate hikes or sudden oil-price
      changes—move through the system using Impulse Response Functions (IRF).
    </p>
    <p>
      To validate the model’s robustness and accuracy through Out-of-Sample
      Forecast Evaluation (2020-2025).
    </p>
    <h2 id="step-1-data-transformation">Step 1: Data Transformation</h2>
    <p>
      Raw economic data often comes in different scales and trends. To prepare
      the data for the VAR model, we applied transformations to ensure
      “stationarity”. We took the first difference for the Fed Funds Rate,
      Unemployment Rate, and Inflation Rate. For Real Wages and Oil Prices, we
      used log-differences.
    </p>
    <table style="width: 98%">
      <caption>
        Transformed Data (First Differences)
      </caption>
      <colgroup>
        <col style="width: 15%" />
        <col style="width: 15%" />
        <col style="width: 14%" />
        <col style="width: 16%" />
        <col style="width: 20%" />
        <col style="width: 16%" />
      </colgroup>
      <thead>
        <tr>
          <th style="text-align: left">date</th>
          <th style="text-align: right">d_Fed_Rate</th>
          <th style="text-align: right">d_Oil_Pct</th>
          <th style="text-align: right">d_Inflation</th>
          <th style="text-align: right">d_Unemployment</th>
          <th style="text-align: right">d_Real_Wage</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="text-align: left">1990-02-01</td>
          <td style="text-align: right">0.01</td>
          <td style="text-align: right">-0.0633</td>
          <td style="text-align: right">-0.5580</td>
          <td style="text-align: right">-0.1</td>
          <td style="text-align: right">0.0004</td>
        </tr>
        <tr>
          <td style="text-align: left">1990-03-01</td>
          <td style="text-align: right">0.04</td>
          <td style="text-align: right">-0.0648</td>
          <td style="text-align: right">0.0766</td>
          <td style="text-align: right">-0.1</td>
          <td style="text-align: right">-0.0020</td>
        </tr>
        <tr>
          <td style="text-align: left">1990-04-01</td>
          <td style="text-align: right">-0.02</td>
          <td style="text-align: right">-0.0871</td>
          <td style="text-align: right">-0.2355</td>
          <td style="text-align: right">0.2</td>
          <td style="text-align: right">-0.0027</td>
        </tr>
        <tr>
          <td style="text-align: left">1990-05-01</td>
          <td style="text-align: right">-0.08</td>
          <td style="text-align: right">-0.0151</td>
          <td style="text-align: right">-0.0781</td>
          <td style="text-align: right">0.0</td>
          <td style="text-align: right">0.0010</td>
        </tr>
        <tr>
          <td style="text-align: left">1990-06-01</td>
          <td style="text-align: right">0.11</td>
          <td style="text-align: right">-0.0695</td>
          <td style="text-align: right">0.4645</td>
          <td style="text-align: right">-0.2</td>
          <td style="text-align: right">-0.0013</td>
        </tr>
        <tr>
          <td style="text-align: left">1990-07-01</td>
          <td style="text-align: right">-0.14</td>
          <td style="text-align: right">0.1160</td>
          <td style="text-align: right">-0.1578</td>
          <td style="text-align: right">0.3</td>
          <td style="text-align: right">-0.0032</td>
        </tr>
      </tbody>
    </table>
    <pre><code>## 
## --- Data Dimensions ---
## Observations: 425
## Variables: 6</code></pre>
    <h2 id="step-2-stationarity-test-adf">Step 2: Stationarity Test (ADF)</h2>
    <p>
      We used the Augmented Dickey-Fuller (ADF) test to check for unit roots.
      The tests returned P-values less than 0.05 for all variables, confirming
      stationarity.
    </p>
    <pre><code>## --- Augmented Dickey-Fuller Test Results ---
## Warning in adf.test(series, alternative = &quot;stationary&quot;): p-value smaller than
## printed p-value
## Variable: Oil % Chg       | P-value: 0.0100 | Result: Stationary (Reject H0) ✅
## Warning in adf.test(series, alternative = &quot;stationary&quot;): p-value smaller than
## printed p-value
## Variable: Delta Unemp     | P-value: 0.0100 | Result: Stationary (Reject H0) ✅
## Warning in adf.test(series, alternative = &quot;stationary&quot;): p-value smaller than
## printed p-value
## Variable: Delta Inflation | P-value: 0.0100 | Result: Stationary (Reject H0) ✅
## Warning in adf.test(series, alternative = &quot;stationary&quot;): p-value smaller than
## printed p-value
## Variable: Delta Real Wage | P-value: 0.0100 | Result: Stationary (Reject H0) ✅
## Warning in adf.test(series, alternative = &quot;stationary&quot;): p-value smaller than
## printed p-value
## Variable: Delta Fed Rate  | P-value: 0.0100 | Result: Stationary (Reject H0) ✅</code></pre>
    <h2 id="step-3-model-specification-training-train-validation">
      Step 3: Model Specification &amp; Training (Train + Validation)
    </h2>
    <p>
      Requirement: The model is fitted on the Train + Validation data
      (Historical data up to Jan 1, 2020). The period from 2020 to 2025 is
      reserved strictly for testing.
    </p>
    <pre><code>## Training Set End Date: 2019-12-01
## AIC suggested lag: 5
## Selected lag order p = 13
## 
## --- Model Fit Statistics ---</code></pre>
    <table style="width: 96%">
      <caption>
        Model Performance Metrics (Training Data)
      </caption>
      <colgroup>
        <col style="width: 23%" />
        <col style="width: 23%" />
        <col style="width: 12%" />
        <col style="width: 18%" />
        <col style="width: 18%" />
      </colgroup>
      <thead>
        <tr>
          <th></th>
          <th style="text-align: left">Equation</th>
          <th style="text-align: right">Adj_R2</th>
          <th style="text-align: right">AIC_System</th>
          <th style="text-align: right">BIC_System</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>d_Fed_Rate</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.4456</td>
          <td style="text-align: right">-5175.747</td>
          <td style="text-align: right">-3906.422</td>
        </tr>
        <tr>
          <td>d_Oil_Pct</td>
          <td style="text-align: left">d_Oil_Pct</td>
          <td style="text-align: right">0.0977</td>
          <td style="text-align: right">-5175.747</td>
          <td style="text-align: right">-3906.422</td>
        </tr>
        <tr>
          <td>d_Inflation</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.4532</td>
          <td style="text-align: right">-5175.747</td>
          <td style="text-align: right">-3906.422</td>
        </tr>
        <tr>
          <td>d_Unemployment</td>
          <td style="text-align: left">d_Unemployment</td>
          <td style="text-align: right">0.2119</td>
          <td style="text-align: right">-5175.747</td>
          <td style="text-align: right">-3906.422</td>
        </tr>
        <tr>
          <td>d_Real_Wage</td>
          <td style="text-align: left">d_Real_Wage</td>
          <td style="text-align: right">0.2343</td>
          <td style="text-align: right">-5175.747</td>
          <td style="text-align: right">-3906.422</td>
        </tr>
      </tbody>
    </table>
    <pre><code>## 
## PASS: All roots are inside the unit circle. System is stable. ✅</code></pre>
    <h2 id="step-4-granger-causality-tests">Step 4: Granger Causality Tests</h2>
    <p>
      Using the model trained on pre-2020 data, we analyze the predictive
      relationships.
    </p>
    <table style="width: 71%">
      <caption>
        Granger Causality Test Results (Pre-2020 Training)
      </caption>
      <colgroup>
        <col style="width: 37%" />
        <col style="width: 13%" />
        <col style="width: 19%" />
      </colgroup>
      <thead>
        <tr>
          <th style="text-align: left">Hypothesis</th>
          <th style="text-align: right">P_Value</th>
          <th style="text-align: left">Significant</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="text-align: left">Fed Rate predicts others</td>
          <td style="text-align: right">0.0370</td>
          <td style="text-align: left">TRUE</td>
        </tr>
        <tr>
          <td style="text-align: left">Unemployment predicts others</td>
          <td style="text-align: right">0.1191</td>
          <td style="text-align: left">FALSE</td>
        </tr>
        <tr>
          <td style="text-align: left">Inflation predicts others</td>
          <td style="text-align: right">0.0238</td>
          <td style="text-align: left">TRUE</td>
        </tr>
        <tr>
          <td style="text-align: left">Oil Price predicts others</td>
          <td style="text-align: right">0.0000</td>
          <td style="text-align: left">TRUE</td>
        </tr>
        <tr>
          <td style="text-align: left">Real Wage predicts others</td>
          <td style="text-align: right">0.0950</td>
          <td style="text-align: left">FALSE</td>
        </tr>
      </tbody>
    </table>
    <h2 id="step-5-impulse-response-analysis">
      Step 5: Impulse Response Analysis
    </h2>
    <p>
      Impulse Response Functions (IRF) visualize how shocks ripple through the
      economy based on the structural relationships learned from the training
      period.
    </p>
    <pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
    <p>
      <img
        src="media/media/image35.png"
      />
    </p>
    <h2 id="step-6-walk-forward-forecast-validation-2020-2025">
      Step 6: Walk-Forward Forecast Validation (2020-2025)
    </h2>
    <p>
      To rigorously test the model, we perform a Rolling Walk-Forward Validation
      on the test set (2020-2025).
    </p>
    <p>
      We start at Jan 2020, forecast 12 months ahead, and compare to actuals.
    </p>
    <p>
      We then move forward one month, refit (or re-predict), and forecast again.
    </p>
    <p>We aggregate the errors by Forecast Horizon (1 to 12 months).</p>
    <pre><code>## Running Walk-Forward Validation from 2020-01-01 to end of data...
## 
## --- Forecast Accuracy by Horizon (2020-2025) ---</code></pre>
    <table style="width: 58%">
      <caption>
        Validation Results: RMSE &amp; MAE by Horizon (Selected Variables)
      </caption>
      <colgroup>
        <col style="width: 13%" />
        <col style="width: 19%" />
        <col style="width: 12%" />
        <col style="width: 12%" />
      </colgroup>
      <thead>
        <tr>
          <th style="text-align: right">Horizon</th>
          <th style="text-align: left">Variable</th>
          <th style="text-align: right">MAE</th>
          <th style="text-align: right">RMSE</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="text-align: right">1</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.2405</td>
          <td style="text-align: right">0.3907</td>
        </tr>
        <tr>
          <td style="text-align: right">2</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.3028</td>
          <td style="text-align: right">0.4858</td>
        </tr>
        <tr>
          <td style="text-align: right">3</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.2860</td>
          <td style="text-align: right">0.5000</td>
        </tr>
        <tr>
          <td style="text-align: right">4</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.2877</td>
          <td style="text-align: right">0.5306</td>
        </tr>
        <tr>
          <td style="text-align: right">5</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.2842</td>
          <td style="text-align: right">0.6105</td>
        </tr>
        <tr>
          <td style="text-align: right">6</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.2973</td>
          <td style="text-align: right">0.6875</td>
        </tr>
        <tr>
          <td style="text-align: right">7</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.3051</td>
          <td style="text-align: right">0.8401</td>
        </tr>
        <tr>
          <td style="text-align: right">8</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.3267</td>
          <td style="text-align: right">1.0809</td>
        </tr>
        <tr>
          <td style="text-align: right">9</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.3585</td>
          <td style="text-align: right">1.2926</td>
        </tr>
        <tr>
          <td style="text-align: right">10</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.4371</td>
          <td style="text-align: right">1.6366</td>
        </tr>
        <tr>
          <td style="text-align: right">11</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.5083</td>
          <td style="text-align: right">1.9337</td>
        </tr>
        <tr>
          <td style="text-align: right">12</td>
          <td style="text-align: left">d_Fed_Rate</td>
          <td style="text-align: right">0.5422</td>
          <td style="text-align: right">2.2258</td>
        </tr>
        <tr>
          <td style="text-align: right">1</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.3460</td>
          <td style="text-align: right">0.5022</td>
        </tr>
        <tr>
          <td style="text-align: right">2</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.3833</td>
          <td style="text-align: right">0.5578</td>
        </tr>
        <tr>
          <td style="text-align: right">3</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.4570</td>
          <td style="text-align: right">0.6753</td>
        </tr>
        <tr>
          <td style="text-align: right">4</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.4020</td>
          <td style="text-align: right">0.6361</td>
        </tr>
        <tr>
          <td style="text-align: right">5</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.3777</td>
          <td style="text-align: right">0.6104</td>
        </tr>
        <tr>
          <td style="text-align: right">6</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.3447</td>
          <td style="text-align: right">0.5227</td>
        </tr>
        <tr>
          <td style="text-align: right">7</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.3827</td>
          <td style="text-align: right">0.5775</td>
        </tr>
        <tr>
          <td style="text-align: right">8</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.3701</td>
          <td style="text-align: right">0.6095</td>
        </tr>
        <tr>
          <td style="text-align: right">9</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.4018</td>
          <td style="text-align: right">0.6407</td>
        </tr>
        <tr>
          <td style="text-align: right">10</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.3828</td>
          <td style="text-align: right">0.6200</td>
        </tr>
        <tr>
          <td style="text-align: right">11</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.3535</td>
          <td style="text-align: right">0.5944</td>
        </tr>
        <tr>
          <td style="text-align: right">12</td>
          <td style="text-align: left">d_Inflation</td>
          <td style="text-align: right">0.3653</td>
          <td style="text-align: right">0.5575</td>
        </tr>
      </tbody>
    </table>
    <p>
      <img
        src="media/media/image36.png"
      />
    </p>
    <h2 id="conclusion">Conclusion</h2>
    <p>
      This study developed a five-variable VAR model validated on out-of-sample
      data from 2020 to 2025.
    </p>
    <p>
      Fit: The model fit statistics (Adjusted
      <span class="math inline">\(R^{2}\)</span>, AIC, BIC) on the training set
      indicate reasonable explanatory power for monthly differenced data.
    </p>
    <p>
      Dynamics: Impulse response analysis confirms significant delayed effects
      of monetary policy on unemployment and inflation.
    </p>
    <p>
      Validation: The walk-forward analysis shows the error (RMSE) typically
      increasing with the forecast horizon, which is expected. This validation
      on the volatile 2020-2025 period demonstrates the model’s capabilities and
      limitations in handling structural breaks like the COVID-19 pandemic.
    </p>
    <h1 id="yield-curve-based-recession-prediction-3-month-forecast">
      Yield Curve-Based Recession Prediction (3-Month Forecast)
    </h1>
    <h2 id="introduction-and-motivation">Introduction and Motivation</h2>
    <p>
      A recession is generally defined by the NBER as a significant decline in
      economic activity spread across the economy, lasting more than a few
      months. Beyond the technical definition, recessions have profound societal
      impacts: rising unemployment, reduced household income, and business
      failures.
    </p>
    <p>Why Early Detection Matters:</p>
    <p>
      For Policymakers: An early warning system allows central banks and
      governments to implement counter-cyclical measures (such as interest rate
      cuts or fiscal stimulus) before the damage becomes deep.
    </p>
    <p>
      For Businesses: Companies can adjust inventory levels, manage cash flow,
      and freeze hiring in anticipation of lower demand.
    </p>
    <p>
      For Households: Individuals can increase savings and reduce discretionary
      spending to prepare for potential income instability.
    </p>
    <p>
      The goal of this project is to build a recession prediction model based on
      a Probit regression framework with a three-month forecast horizon. In
      addition to the classical yield spread, we incorporate real-economy
      indicators—such as GDP trend, labor market conditions (unemployment gap),
      and inflation and oil price dynamics—to construct a robust multivariate
      forecasting system.
    </p>
    <p>
      We use U.S. economic data from 1990 to the present. Data from 1990–2018
      are used for model training (in-sample), while data from 2018 onward serve
      as the out-of-sample test set.
    </p>
    <h2 id="step-1-2-data-engineering">Step 1 &amp; 2: Data Engineering</h2>
    <p>
      Raw monthly economic data often contain substantial noise and are released
      with lags. To build a reliable forecasting model, we applied the following
      preprocessing steps:
    </p>
    <p>
      Target Variable Construction: We define Target_Recession as whether an
      NBER recession occurs three months ahead (<span class="math inline"
        >\(t + 3\)</span
      >). Using information at time <span class="math inline">\(t\)</span> to
      predict the state at <span class="math inline">\(t + 3\)</span> ensures
      genuine forward-looking value.
    </p>
    <p>
      Data Smoothing: Monthly economic indicators can fluctuate sharply. Key
      variables (yield spread, oil prices, GDP trend) are smoothed using a
      3-month rolling mean.
    </p>
    <p>
      Lag Adjustment: For GDP_Trend, we applied a lag to simulate real-world
      data availability (avoiding data leakage).
    </p>
    <p>
      Yield Spread Momentum: We constructed Spread_Change (<span
        class="math inline"
        >\(Spread_{t} - Spread_{t - 3}\)</span
      >) to capture the velocity of yield curve deterioration.
    </p>
    <h2 id="step-3-model-selection-aic">Step 3: Model Selection (AIC)</h2>
    <p>
      We built four Probit models of increasing complexity. Based on the Akaike
      Information Criterion (AIC), the model specification including Spread,
      Spread_Change, GDP_Trend, Real_Fed_Rate, Unemp_Gap, and Oil_YoY achieved
      the lowest AIC and the best overall fit.
    </p>
    <pre><code>## ### Model Comparison Results
## 
## 
## Table: AIC Comparison
## 
## |Model_Name     | AIC_Value|
## |:--------------|---------:|
## |Simple Model   |  182.5489|
## |Complex1 Model |  128.4967|
## |Complex2 Model |  124.7051|
## |Complex3 Model |  114.6570|
## 
## ➡️ **Selected Model:** Complex3 Model</code></pre>
    <h2 id="step-4-marginal-effects-variable-importance">
      Step 4: Marginal Effects &amp; Variable Importance
    </h2>
    <p>
      To understand which variables contribute most to the prediction, we
      calculated the Average Marginal Effects (AME). The bar chart below
      visualizes the impact of a one-unit increase in each variable on the
      probability of a recession.
    </p>
    <p>
      <img
        src="media/media/image37.png"
      />
    </p>
    <p>Analysis of Key Drivers:</p>
    <p>
      Spread_Change (Momentum): As shown in the chart, Spread_Change is a strong
      positive predictor. This suggests that the velocity of yield curve
      flattening/inversion is often a more critical warning signal than the
      spread level itself.
    </p>
    <p>
      GDP_Trend: A positive trend in Real GDP is the strongest protective factor
      (negative coefficient), significantly reducing recession probability.
    </p>
    <p>
      Oil_YoY: Positive oil price shocks also contribute to increased recession
      risk.
    </p>
    <h2 id="step-5-threshold-optimization-and-performance-metrics">
      Step 5: Threshold Optimization and Performance Metrics
    </h2>
    <p>
      We used Youden’s Index to identify an optimal threshold to balance
      Sensitivity and Specificity.
    </p>
    <p>
      <img
        src="media/media/image38.png"

      />
    </p>
    <h2 id="step-6-visualization-and-analysis">
      Step 6: Visualization and Analysis
    </h2>
    <p>
      The final time-series visualization compares the model’s predicted
      recession probabilities with actual NBER recession periods.
    </p>
    <p>
      <img
        src="media/media/image39.png"
   
      />
    </p>
    <h2 id="conclusion-1">Conclusion</h2>
    <p>
      Although the model performs strongly across historical cycles, its
      elevated recession probabilities during 2023–2024 contrast sharply with
      the economy’s actual robustness. This discrepancy—labeled as a “False
      Alarm”—likely reflects structural shifts in the post-pandemic economy,
      suggesting that traditional transmission channels may have become
      “decoupled” or weakened.
    </p>
    <p>
      Practical Value: Despite the recent “false alarm,” the model maintains
      high sensitivity in identifying historical downturns. For stakeholders,
      this implies that while the model may occasionally signal caution during
      “soft landings,” it effectively ensures that no genuine recession is
      missed. This “safety-first” characteristic makes it a valuable heuristic
      tool for risk management scenarios where missing a crisis (False Negative)
      is more costly than preparing for one that doesn’t happen.
    </p>
    <h1 id="project-conclusion">Project Conclusion</h1>
    <p>
      The project began by attempting to explain inflation using the traditional
      Phillips curve, which historically linked unemployment to changes in
      inflation. However, this approach quickly failed to capture the modern
      dynamics of inflation as the economy has changed since the 1960s. We
      decided to add variables to the study that include global linkages,
      Treasury yields, GDP growth, energy prices, and monetary policy variables.
      To more fully assess and forecast inflation, we developed three
      complementary models, each chosen for a specific analytical purpose:
    </p>
    <p>
      <strong>SARIMAX for Precision Forecasting</strong>: Utilized for its
      ability to capture short-term persistence. The model demonstrated that
      inflation is highly autoregressive, providing excellent short-turn (h &lt;
      4) forecasts, and effectively accounting for the weak but persistent
      seasonality in the data.
    </p>
    <p>
      <strong
        >Linear regression for interpretation and structural
        identification</strong
      >. Served as the primary tool for feature selection and interpretability.
      Variable models quantify how oil, GDP growth, wages, and interest rates
      affect inflation. Useful for understanding structural relationships that
      models such as VAR and SARIMA can hide.
    </p>
    <p>
      <strong>VAR for dynamic system modeling</strong>. Models the joint
      evolution of several economic variables. The model provides stable
      medium-term forecasts and captures the feedback loops between policy rates
      (e.g., oil shocks or rate hikes). We find that energy markets are the
      strongest predictors of inflation: a rise in oil or natural gas prices
      leads to a noticeable increase in monthly inflation, and stronger GDP
      growth raises inflation with an eight-month delay. Inflation also exhibits
      strong short-run persistence, while higher year-over-year inflation exerts
      a mild corrective force, helping stabilize monthly price changes.
    </p>
    <p>
      Ultimately, this comparative analysis demonstrates that no single
      statistical framework suffices for a system as complex as the US
      macroeconomy. We observed a clear trade-off between model interpretability
      (Linear Regression), short-run forecasting (SARIMAX), and dynamic
      predictive power (VAR). While our models successfully captured the
      autoregressive nature of inflation and identified significant lag
      structures, they were constrained by the strict assumptions of linearity
      and the necessity of stationarity transformations, which filtered out
      long-term equilibrium signals. This project highlights that robust
      statistical analysis requires not just a single ‘best’ model, but a
      diverse ensemble of approaches, and points to the necessity of future
      non-linear methods, such as Markov Switching AR, Machine Learning and
      Structural VECM, to overcome the limitations of classical econometrics in
      the presence of structural breaks.
    </p>
    <h1 id="limitations">Limitations</h1>
    <p>
      Despite the strengths of the models developed in this study, several
      limitations should be acknowledged. The U.S. economy has experienced
      substantial structural changes, particularly since the 1980s and during
      the COVID-19 period. Traditional time-series frameworks such as linear
      regression, SARIMAX, and VAR assume relatively stable relationships over
      time, an assumption that may be violated in the presence of regime shifts,
      policy changes, or supply-side disruptions. Although early data were
      omitted to reduce the impact of structural breaks from the 1970s and early
      1980s, structural instability remains a concern and may distort estimated
      relationships.
    </p>
    <p>
      Model performance is also affected by lag selection and differencing. Lags
      that lacked statistical significance were removed to avoid overfitting;
      however, this filtering may reduce predictive power when economic effects
      operate with long or variable delays. In the VAR framework, differencing
      the data further limits the analysis to short-run dynamics and leads to a
      loss of long-term equilibrium information.
    </p>
    <p>
      Forecasting limitations are particularly evident over longer horizons.
      SARIMAX models tend to accumulate errors rapidly as the forecast horizon
      increases, with high persistence and weak seasonality causing forecasts to
      stagnate. VAR models, while capturing multivariate interactions, exhibit
      weaker dependence structures and higher residual variance, resulting in a
      less precise fit for the inflation equation compared to SARIMAX.
    </p>
    <p>
      Finally, all models considered rely on linear assumptions, whereas
      real-world economic dynamics are often nonlinear. This simplification,
      combined with the unprecedented volatility and policy responses during the
      COVID-19 shock, may cause models to misinterpret temporary disruptions as
      structural features of the inflation process.
    </p>
    <h1 id="future-works">Future works</h1>
    <ol type="1">
      <li>
        <p>
          <strong>Markov-Switching Models:</strong> Use Markov-Switching VAR/AR
          to accommodate structural breaks, allowing for the analysis of the
          full historical time series.
        </p>
      </li>
      <li>
        <p>
          <strong>Machine Learning Models:</strong> Implement Long Short-Term
          Memory (LSTM) networks or Random Forest Regression. These models
          naturally capture non-linear interactions and may outperform ARIMA in
          long-horizon forecasting.
        </p>
      </li>
      <li>
        <p>
          <strong>Structural VECM:</strong> Develop a Structural VECM (SVECM) to
          analyze long-term equilibrium dynamics while simultaneously
          identifying structural inflationary shocks.
        </p>
      </li>
      <li>
        <p>
          <strong>Explainable AI:</strong> Use Shapley Additive explanations
          (SHAP) to analyze the effect size and contribution of each predictor
          variable on the target.
        </p>
      </li>
    </ol>
  </body>
</html>
